// website/src/pages/components/mod.rs
// Component showcase pages
// Auto-generated by scripts/generate_bulk_imports.py
//
// 批量导入策略：使用include!宏进行编译时导入
//

include!("alert.rs");
include!("badge.rs");
include!("basic.rs");
include!("breadcrumb.rs");
include!("button.rs");
include!("card.rs");
include!("data.rs");
include!("feedback.rs");
include!("input.rs");
include!("layout.rs");
include!("menu.rs");
include!("navigation.rs");
include!("overview.rs");
include!("tabs.rs");
include!("toast.rs");
include!("tooltip.rs");

// Re-export all components

pub use alert::*;
pub use badge::*;
pub use basic::*;
pub use breadcrumb::*;
pub use button::*;
pub use card::*;
pub use data::*;
pub use feedback::*;
pub use input::*;
pub use layout::*;
pub use menu::*;
pub use navigation::*;
pub use overview::*;
pub use tabs::*;
pub use toast::*;
pub use tooltip::*;
