// website/src/pages/demos/mod.rs
// Demo pages
// Auto-generated by scripts/generate_bulk_imports.py
//
// 批量导入策略：使用include!宏进行编译时导入
//

include!("showcase.rs");

// Re-export all

pub use showcase::*;
