[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-web-wrapper"
version = "0.1.0"

[dependencies]
anyhow = "^1"
chrono = "^0.4"
env_logger = "^0.10"
log = "^0.4"
tokio = {version = "^1", features = ["macros", "rt-multi-thread"]}

[[bin]]
name = "build-server"
path = "bin/build.rs"

[[bin]]
name = "run-server"
path = "bin/run.rs"
