[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
script = '''
#!@duckscript

exec cargo build --package hikari-website --target wasm32-unknown-unknown --release
exec wasm-bindgen --out-dir ./target/wasm32-html --out-name a --target no-modules --no-typescript --no-modules-global __wasm_vendor_entry ./target/wasm32-unknown-unknown/release/hikari_website.wasm
'''

[tasks.serve]
script = '''
#!@duckscript

exec cargo make build
exec cargo run --package hikari-website --example dev
'''
