// Auto-generated by scripts/fetch_tailwindcss.py
// Generated at: 2026-01-09T00:33:47.088216
// Source: https://unpkg.com/tailwindcss@3.4.1/tailwind.css
// Size: 61 bytes

#![allow(dead_code)]

/// Tailwind CSS utility classes
///
/// This module contains the full Tailwind CSS bundle downloaded from the CDN.
/// It provides all utility classes for rapid UI development.
///
/// See: https://tailwindcss.com/docs/utility-first
pub const TAILWIND_CSS: &str = r#"
@tailwind base;

@tailwind components;

@tailwind utilities;

"#;
