version: '3'

volumes:
  db-dev:
  build-cache:

services:
  dynamic:
    build:
      context: ../
      dockerfile: ./tasks/dev.dockerfile
    ports:
      - 80:80
    volumes:
      - ../packages/database:/home/packages/database
      - ../packages/router:/home/packages/router
      - ../packages/utils:/home/packages/utils
      - ../packages/web:/home/packages/web
      - build-cache:/home/target
    environment:
      - DB_HOST=database
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    networks:
      - backend-dev
    depends_on:
      - database
  database:
    image: ceresdb/ceresdb-server
    ports:
      - 3307:3307
    volumes:
      - db-dev:/data
      - ./ceresdb.toml:/etc/ceresdb/ceresdb.toml
    networks:
      - backend-dev

networks:
  backend-dev:
    driver: bridge
