version: '3'

volumes:
  db:

services:
  dynamic:
    build:
      context: ../
      dockerfile: ./tasks/build.dockerfile
    ports:
      - 80:80
    environment:
      - DB_HOST=database
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    networks:
      - backend
    restart: always
    depends_on:
      - database
  database:
    image: ceresdb/ceresdb-server
    expose:
      - 3307
    volumes:
      - db:/data
      - ./ceresdb.toml:/etc/ceresdb/ceresdb.toml
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
