version: '3'

volumes:
  db:

services:
  dynamic:
    build:
      context: ../
      dockerfile: ./tasks/build.dockerfile
    ports:
      - 80:3000
    environment:
      - DB_HOST=database
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    networks:
      - backend
    restart: always
    depends_on:
      - database
  database:
    image: mariadb:lts
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_USER=$DB_USERNAME
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_DATABASE=$DB_DATABASE
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
