use std::sync::LazyLock;

pub use tairitsu_web::i18n::Language;

fn is_german(lang: &Language) -> bool {
    lang.code().starts_with("DE")
}

pub struct ComponentKeys {
    pub button: &'static str,
    pub input: &'static str,
    pub card: &'static str,
    pub menu: &'static str,
    pub switch: &'static str,
    pub avatar: &'static str,
    pub tag: &'static str,
    pub image: &'static str,
    pub empty: &'static str,
    pub comment: &'static str,
    pub search: &'static str,
    pub number_input: &'static str,
    pub navigation: &'static str,
    pub table: &'static str,
    pub form: &'static str,
    pub feedback: &'static str,
    pub cascader: &'static str,
    pub transfer: &'static str,
    pub collapsible: &'static str,
    pub timeline: &'static str,
    pub tree: &'static str,
    pub pagination: &'static str,
    pub media_player: &'static str,
    pub editor: &'static str,
    pub visualization: &'static str,
    pub zoom_controls: &'static str,
    pub qrcode: &'static str,
    pub display: &'static str,
    pub description_list: &'static str,
    pub data: &'static str,
    pub user_guide: &'static str,
}

pub struct PageKeys {
    pub home: &'static str,
    pub components: &'static str,
    pub system: &'static str,
    pub demos: &'static str,
    pub animations: &'static str,
    pub interactive: &'static str,
    pub design_system: &'static str,
    pub color_palette: &'static str,
    pub css_utilities: &'static str,
    pub icons: &'static str,
    pub i18n: &'static str,
    pub not_found: &'static str,
}

pub struct LabelKeys {
    pub explore_components: &'static str,
    pub layer_base: &'static str,
    pub layer_composed: &'static str,
    pub layer_complex: &'static str,
    pub overview: &'static str,
    pub complete: &'static str,
    pub code: &'static str,
    pub language: &'static str,
    pub status: &'static str,
    pub submit: &'static str,
    pub cancel: &'static str,
    pub confirm: &'static str,
    pub close: &'static str,
    pub search_placeholder: &'static str,
    pub loading: &'static str,
    pub no_data: &'static str,
}

pub struct DescriptionKeys {
    pub button: &'static str,
    pub input: &'static str,
    pub card: &'static str,
    pub switch: &'static str,
    pub avatar: &'static str,
    pub tag: &'static str,
    pub search: &'static str,
    pub navigation: &'static str,
    pub form: &'static str,
    pub feedback: &'static str,
    pub cascader: &'static str,
    pub transfer: &'static str,
    pub collapsible: &'static str,
    pub timeline: &'static str,
    pub tree: &'static str,
    pub pagination: &'static str,
    pub media_player: &'static str,
    pub editor: &'static str,
    pub visualization: &'static str,
    pub zoom_controls: &'static str,
}

pub struct I18nKeys {
    pub components: ComponentKeys,
    pub pages: PageKeys,
    pub labels: LabelKeys,
    pub descriptions: DescriptionKeys,
}

static KEYS_EN: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "Button",
        input: "Input",
        card: "Card",
        menu: "Menu",
        switch: "Switch",
        avatar: "Avatar",
        tag: "Tag",
        image: "Image",
        empty: "Empty",
        comment: "Comment",
        search: "Search",
        number_input: "Number Input",
        navigation: "Navigation",
        table: "Table",
        form: "Form",
        feedback: "Feedback",
        cascader: "Cascader",
        transfer: "Transfer",
        collapsible: "Collapsible",
        timeline: "Timeline",
        tree: "Tree",
        pagination: "Pagination",
        media_player: "Media Player",
        editor: "Editor",
        visualization: "Visualization",
        zoom_controls: "Zoom Controls",
        qrcode: "QRCode",
        display: "Display",
        description_list: "Description List",
        data: "Data",
        user_guide: "User Guide",
    },
    pages: PageKeys {
        home: "Home",
        components: "Components",
        system: "System",
        demos: "Demos",
        animations: "Animations",
        interactive: "Interactive",
        design_system: "Design System",
        color_palette: "Color Palette",
        css_utilities: "CSS Utilities",
        icons: "Icons",
        i18n: "i18n",
        not_found: "Not Found",
    },
    labels: LabelKeys {
        explore_components: "Explore Components",
        layer_base: "Layer 1 \u{2014} Base Components",
        layer_composed: "Layer 2 \u{2014} Composed Components",
        layer_complex: "Layer 3 \u{2014} Complex Components",
        overview: "Overview",
        complete: "Complete",
        code: "Code",
        language: "Language",
        status: "Status",
        submit: "Submit",
        cancel: "Cancel",
        confirm: "Confirm",
        close: "Close",
        search_placeholder: "Search...",
        loading: "Loading...",
        no_data: "No data",
    },
    descriptions: DescriptionKeys {
        button: "Primary action trigger with variants: primary, secondary, danger, ghost.",
        input: "Text entry field with validation states and placeholder support.",
        card: "Container for grouping related content with optional header and footer.",
        switch: "Boolean toggle control.",
        avatar: "User or entity representation with image and initials fallback.",
        tag: "Compact label for categorisation or status display.",
        search: "Search input with instant filtering support.",
        navigation: "Tabs, breadcrumbs, steps, and menu components.",
        form: "Form builder with validation, layout, and submission handling.",
        feedback: "Toast notifications, alerts, progress bars, and spinners.",
        cascader: "Hierarchical multi-level select picker.",
        transfer: "Dual-panel transfer widget for moving items between lists.",
        collapsible: "Accordion / collapse panels with animation.",
        timeline: "Chronological event display.",
        tree: "Hierarchical tree view with expand / collapse.",
        pagination: "Page navigation control.",
        media_player: "Video and audio player with custom controls.",
        editor: "Rich text and markdown editor with formatting toolbar.",
        visualization: "Charts, graphs, and data visualisation primitives.",
        zoom_controls: "Zoom in, zoom out, and reset controls for canvas or viewer.",
    },
};

static KEYS_ZH_CN: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "按钮",
        input: "输入框",
        card: "卡片",
        menu: "菜单",
        switch: "开关",
        avatar: "头像",
        tag: "标签",
        image: "图片",
        empty: "空状态",
        comment: "评论",
        search: "搜索",
        number_input: "数字输入",
        navigation: "导航",
        table: "表格",
        form: "表单",
        feedback: "反馈",
        cascader: "级联选择",
        transfer: "穿梭框",
        collapsible: "折叠面板",
        timeline: "时间线",
        tree: "树形控件",
        pagination: "分页",
        media_player: "媒体播放器",
        editor: "编辑器",
        visualization: "可视化",
        zoom_controls: "缩放控件",
        qrcode: "二维码",
        display: "展示",
        description_list: "描述列表",
        data: "数据",
        user_guide: "使用指南",
    },
    pages: PageKeys {
        home: "首页",
        components: "组件",
        system: "系统",
        demos: "示例",
        animations: "动画",
        interactive: "交互",
        design_system: "设计系统",
        color_palette: "色彩",
        css_utilities: "CSS 工具类",
        icons: "图标",
        i18n: "国际化",
        not_found: "页面未找到",
    },
    labels: LabelKeys {
        explore_components: "浏览组件",
        layer_base: "第一层 \u{2014} 基础组件",
        layer_composed: "第二层 \u{2014} 组合组件",
        layer_complex: "第三层 \u{2014} 复杂组件",
        overview: "概览",
        complete: "完成",
        code: "代码",
        language: "语言",
        status: "状态",
        submit: "提交",
        cancel: "取消",
        confirm: "确认",
        close: "关闭",
        search_placeholder: "搜索...",
        loading: "加载中...",
        no_data: "暂无数据",
    },
    descriptions: DescriptionKeys {
        button: "主要操作触发器，支持主要、次要、危险、幽灵等变体。",
        input: "文本输入字段，支持验证状态和占位符。",
        card: "用于分组相关内容的容器，支持可选的头部和底部。",
        switch: "布尔值切换控件。",
        avatar: "用户或实体标识，支持图片和首字母回退显示。",
        tag: "用于分类或状态显示的紧凑标签。",
        search: "支持即时过滤的搜索输入框。",
        navigation: "标签页、面包屑、步骤条和菜单组件。",
        form: "支持验证、布局和提交处理的表单构建器。",
        feedback: "消息通知、警告、进度条和加载指示器。",
        cascader: "层级多级选择器。",
        transfer: "双面板穿梭框，用于在列表间移动项目。",
        collapsible: "带动画的手风琴/折叠面板。",
        timeline: "按时间顺序显示事件。",
        tree: "支持展开/折叠的层级树形视图。",
        pagination: "页面导航控件。",
        media_player: "支持自定义控件的视频和音频播放器。",
        editor: "带格式化工具栏的富文本和 Markdown 编辑器。",
        visualization: "图表、图形和数据可视化基础组件。",
        zoom_controls: "画布或查看器的放大、缩小和重置控件。",
    },
};

static KEYS_ZH_TW: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "按鈕",
        input: "輸入框",
        card: "卡片",
        menu: "選單",
        switch: "開關",
        avatar: "頭像",
        tag: "標籤",
        image: "圖片",
        empty: "空狀態",
        comment: "評論",
        search: "搜尋",
        number_input: "數字輸入",
        navigation: "導航",
        table: "表格",
        form: "表單",
        feedback: "回饋",
        cascader: "級聯選擇",
        transfer: "穿梭框",
        collapsible: "折疊面板",
        timeline: "時間線",
        tree: "樹形控制項",
        pagination: "分頁",
        media_player: "媒體播放器",
        editor: "編輯器",
        visualization: "視覺化",
        zoom_controls: "縮放控制項",
        qrcode: "二維碼",
        display: "展示",
        description_list: "描述列表",
        data: "資料",
        user_guide: "使用指南",
    },
    pages: PageKeys {
        home: "首頁",
        components: "元件",
        system: "系統",
        demos: "範例",
        animations: "動畫",
        interactive: "互動",
        design_system: "設計系統",
        color_palette: "色彩",
        css_utilities: "CSS 工具類",
        icons: "圖示",
        i18n: "國際化",
        not_found: "頁面未找到",
    },
    labels: LabelKeys {
        explore_components: "瀏覽元件",
        layer_base: "第一層 \u{2014} 基礎元件",
        layer_composed: "第二層 \u{2014} 組合元件",
        layer_complex: "第三層 \u{2014} 複雜元件",
        overview: "概覽",
        complete: "完成",
        code: "程式碼",
        language: "語言",
        status: "狀態",
        submit: "提交",
        cancel: "取消",
        confirm: "確認",
        close: "關閉",
        search_placeholder: "搜尋...",
        loading: "載入中...",
        no_data: "暫無資料",
    },
    descriptions: DescriptionKeys {
        button: "主要操作觸發器，支援主要、次要、危險、幽靈等變體。",
        input: "文字輸入欄位，支援驗證狀態和佔位符。",
        card: "用於分組相關內容的容器，支援可選的頭部和底部。",
        switch: "布林值切換控制項。",
        avatar: "使用者或實體標識，支援圖片和首字母回退顯示。",
        tag: "用於分類或狀態顯示的緊湊標籤。",
        search: "支援即時過濾的搜尋輸入框。",
        navigation: "標籤頁、麵包屑、步驟條和選單元件。",
        form: "支援驗證、佈局和提交處理的表單建構器。",
        feedback: "訊息通知、警告、進度條和載入指示器。",
        cascader: "層級多級選擇器。",
        transfer: "雙面板穿梭框，用於在列表間移動項目。",
        collapsible: "帶動畫的手風琴/折疊面板。",
        timeline: "按時間順序顯示事件。",
        tree: "支援展開/折疊的層級樹形檢視。",
        pagination: "頁面導航控制項。",
        media_player: "支援自訂控制項的影片和音訊播放器。",
        editor: "帶格式化工具列的富文字和 Markdown 編輯器。",
        visualization: "圖表、圖形和資料視覺化基礎元件。",
        zoom_controls: "畫布或檢視器的放大、縮小和重置控制項。",
    },
};

static KEYS_JA: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "ボタン",
        input: "入力",
        card: "カード",
        menu: "メニュー",
        switch: "スイッチ",
        avatar: "アバター",
        tag: "タグ",
        image: "画像",
        empty: "空状態",
        comment: "コメント",
        search: "検索",
        number_input: "数値入力",
        navigation: "ナビゲーション",
        table: "テーブル",
        form: "フォーム",
        feedback: "フィードバック",
        cascader: "カスケーダー",
        transfer: "転送",
        collapsible: "折りたたみ",
        timeline: "タイムライン",
        tree: "ツリー",
        pagination: "ページネーション",
        media_player: "メディアプレーヤー",
        editor: "エディター",
        visualization: "ビジュアライゼーション",
        zoom_controls: "ズームコントロール",
        qrcode: "QRコード",
        display: "表示",
        description_list: "記述リスト",
        data: "データ",
        user_guide: "ユーザーガイド",
    },
    pages: PageKeys {
        home: "ホーム",
        components: "コンポーネント",
        system: "システム",
        demos: "デモ",
        animations: "アニメーション",
        interactive: "インタラクティブ",
        design_system: "デザインシステム",
        color_palette: "カラーパレット",
        css_utilities: "CSSユーティリティ",
        icons: "アイコン",
        i18n: "国際化",
        not_found: "ページが見つかりません",
    },
    labels: LabelKeys {
        explore_components: "コンポーネントを見る",
        layer_base: "レイヤー 1 \u{2014} 基本コンポーネント",
        layer_composed: "レイヤー 2 \u{2014} 組み合わせコンポーネント",
        layer_complex: "レイヤー 3 \u{2014} 複合コンポーネント",
        overview: "概要",
        complete: "完了",
        code: "コード",
        language: "言語",
        status: "ステータス",
        submit: "送信",
        cancel: "キャンセル",
        confirm: "確認",
        close: "閉じる",
        search_placeholder: "検索...",
        loading: "読み込み中...",
        no_data: "データなし",
    },
    descriptions: DescriptionKeys {
        button: "プライマリ、セカンダリ、デンジャー、ゴーストなどのバリエーションを持つアクションボタン。",
        input: "検証状態とプレースホルダーをサポートするテキスト入力フィールド。",
        card: "関連するコンテンツをグループ化するコンテナ。",
        switch: "ブール値の切替コントロール。",
        avatar: "画像とイニシャルフォールバックをサポートするユーザー表現。",
        tag: "分類やステータス表示用のコンパクトなラベル。",
        search: "即時フィルタリングをサポートする検索入力。",
        navigation: "タブ、パンくずリスト、ステップ、メニューコンポーネント。",
        form: "検証、レイアウト、送信処理を備えたフォームビルダー。",
        feedback: "トースト通知、アラート、プログレスバー、スピナー。",
        cascader: "階層的なマルチレベル選択ピッカー。",
        transfer: "リスト間でアイテムを移動するデュアルパネル転送ウィジェット。",
        collapsible: "アニメーション付きのアコーディオン/折りたたみパネル。",
        timeline: "時系列イベント表示。",
        tree: "展開/折りたたみを備えた階層ツリービュー。",
        pagination: "ページナビゲーションコントロール。",
        media_player: "カスタムコントロールを備えた動画・音声プレーヤー。",
        editor: "フォーマットツールバーを備えたリッチテキストおよびMarkdownエディター。",
        visualization: "チャート、グラフ、データ可視化プリミティブ。",
        zoom_controls: "キャンバスやビューアのズームイン、ズームアウト、リセットコントロール。",
    },
};

static KEYS_KO: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "버튼",
        input: "입력",
        card: "카드",
        menu: "메뉴",
        switch: "스위치",
        avatar: "아바타",
        tag: "태그",
        image: "이미지",
        empty: "빈 상태",
        comment: "댓글",
        search: "검색",
        number_input: "숫자 입력",
        navigation: "네비게이션",
        table: "테이블",
        form: "폼",
        feedback: "피드백",
        cascader: "캐스케이더",
        transfer: "이동",
        collapsible: "접이식",
        timeline: "타임라인",
        tree: "트리",
        pagination: "페이지네이션",
        media_player: "미디어 플레이어",
        editor: "에디터",
        visualization: "시각화",
        zoom_controls: "줌 컨트롤",
        qrcode: "QR코드",
        display: "표시",
        description_list: "설명 목록",
        data: "데이터",
        user_guide: "사용자 가이드",
    },
    pages: PageKeys {
        home: "홈",
        components: "컴포넌트",
        system: "시스템",
        demos: "데모",
        animations: "애니메이션",
        interactive: "인터랙티브",
        design_system: "디자인 시스템",
        color_palette: "색상 팔레트",
        css_utilities: "CSS 유틸리티",
        icons: "아이콘",
        i18n: "국제화",
        not_found: "페이지를 찾을 수 없습니다",
    },
    labels: LabelKeys {
        explore_components: "컴포넌트 살펴보기",
        layer_base: "레이어 1 \u{2014} 기본 컴포넌트",
        layer_composed: "레이어 2 \u{2014} 조합 컴포넌트",
        layer_complex: "레이어 3 \u{2014} 복합 컴포넌트",
        overview: "개요",
        complete: "완료",
        code: "코드",
        language: "언어",
        status: "상태",
        submit: "제출",
        cancel: "취소",
        confirm: "확인",
        close: "닫기",
        search_placeholder: "검색...",
        loading: "로딩 중...",
        no_data: "데이터 없음",
    },
    descriptions: DescriptionKeys {
        button: "기본, 보조, 위험, 고스트 등의 변형을 지원하는 작업 버튼.",
        input: "유효성 검사 상태와 플레이스홀더를 지원하는 텍스트 입력 필드.",
        card: "관련 콘텐츠를 그룹화하는 컨테이너.",
        switch: "불리언 토글 컨트롤.",
        avatar: "이미지와 이니셜 폴백을 지원하는 사용자 표현.",
        tag: "분류 또는 상태 표시용 컴팩트 라벨.",
        search: "즉시 필터링을 지원하는 검색 입력.",
        navigation: "탭, 빵가루, 스텝, 메뉴 컴포넌트.",
        form: "유효성 검사, 레이아웃, 제출 처리를 갖춘 폼 빌더.",
        feedback: "토스트 알림, 경고, 진행률 표시줄, 스피너.",
        cascader: "계층적 다중 레벨 선택기.",
        transfer: "목록 간 항목 이동을 위한 듀얼 패널 전송 위젯.",
        collapsible: "애니메이션이 있는 아코디언/접이식 패널.",
        timeline: "시간순 이벤트 표시.",
        tree: "확장/접기를 지원하는 계층 트리 뷰.",
        pagination: "페이지 탐색 컨트롤.",
        media_player: "커스텀 컨트롤을 갖춘 비디오 및 오디오 플레이어.",
        editor: "서식 도구 모음을 갖춘 리치 텍스트 및 Markdown 편집기.",
        visualization: "차트, 그래프 및 데이터 시각화 프리미티브.",
        zoom_controls: "캔버스나 뷰어의 확대, 축소, 초기화 컨트롤.",
    },
};

static KEYS_FR: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "Bouton",
        input: "Champ de saisie",
        card: "Carte",
        menu: "Menu",
        switch: "Interrupteur",
        avatar: "Avatar",
        tag: "Étiquette",
        image: "Image",
        empty: "Vide",
        comment: "Commentaire",
        search: "Recherche",
        number_input: "Saisie numérique",
        navigation: "Navigation",
        table: "Tableau",
        form: "Formulaire",
        feedback: "Retour d'information",
        cascader: "Sélecteur en cascade",
        transfer: "Transfert",
        collapsible: "Réductible",
        timeline: "Chronologie",
        tree: "Arbre",
        pagination: "Pagination",
        media_player: "Lecteur multimédia",
        editor: "Éditeur",
        visualization: "Visualisation",
        zoom_controls: "Contrôles de zoom",
        qrcode: "QR Code",
        display: "Affichage",
        description_list: "Liste descriptive",
        data: "Données",
        user_guide: "Guide utilisateur",
    },
    pages: PageKeys {
        home: "Accueil",
        components: "Composants",
        system: "Système",
        demos: "Démos",
        animations: "Animations",
        interactive: "Interactif",
        design_system: "Système de design",
        color_palette: "Palette de couleurs",
        css_utilities: "Utilitaires CSS",
        icons: "Icônes",
        i18n: "i18n",
        not_found: "Page introuvable",
    },
    labels: LabelKeys {
        explore_components: "Explorer les composants",
        layer_base: "Couche 1 \u{2014} Composants de base",
        layer_composed: "Couche 2 \u{2014} Composants composés",
        layer_complex: "Couche 3 \u{2014} Composants complexes",
        overview: "Vue d'ensemble",
        complete: "Terminé",
        code: "Code",
        language: "Langue",
        status: "Statut",
        submit: "Envoyer",
        cancel: "Annuler",
        confirm: "Confirmer",
        close: "Fermer",
        search_placeholder: "Rechercher...",
        loading: "Chargement...",
        no_data: "Aucune donnée",
    },
    descriptions: DescriptionKeys {
        button:
            "Déclencheur d'action principal avec variantes : primaire, secondaire, danger, fantôme.",
        input: "Champ de saisie texte avec états de validation et support d'espace réservé.",
        card:
            "Conteneur pour regrouper du contenu associé avec en-tête et pied de page optionnels.",
        switch: "Contrôle de basculement booléen.",
        avatar: "Représentation utilisateur avec image et repli par initiales.",
        tag: "Étiquette compacte pour la catégorisation ou l'affichage de statut.",
        search: "Champ de recherche avec filtrage instantané.",
        navigation: "Onglets, fil d'Ariane, étapes et composants de menu.",
        form: "Constructeur de formulaire avec validation, mise en page et gestion de soumission.",
        feedback:
            "Notifications toast, alertes, barres de progression et indicateurs de chargement.",
        cascader: "Sélecteur multi-niveaux hiérarchique.",
        transfer:
            "Widget de transfert à double panneau pour déplacer des éléments entre des listes.",
        collapsible: "Panneaux accordéon/réductibles avec animation.",
        timeline: "Affichage chronologique des événements.",
        tree: "Vue arborescente hiérarchique avec expansion/réduction.",
        pagination: "Contrôle de navigation de page.",
        media_player: "Lecteur vidéo et audio avec contrôles personnalisés.",
        editor: "Éditeur de texte riche et Markdown avec barre d'outils de formatage.",
        visualization: "Graphiques et primitives de visualisation de données.",
        zoom_controls: "Contrôles d'agrandissement, de réduction et de réinitialisation.",
    },
};

static KEYS_DE: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "Schaltfläche",
        input: "Eingabefeld",
        card: "Karte",
        menu: "Menü",
        switch: "Schalter",
        avatar: "Avatar",
        tag: "Etikett",
        image: "Bild",
        empty: "Leer",
        comment: "Kommentar",
        search: "Suche",
        number_input: "Zahleneingabe",
        navigation: "Navigation",
        table: "Tabelle",
        form: "Formular",
        feedback: "Rückmeldung",
        cascader: "Kaskadierer",
        transfer: "Übertragung",
        collapsible: "Einklappbar",
        timeline: "Zeitachse",
        tree: "Baum",
        pagination: "Seitennummerierung",
        media_player: "Medienplayer",
        editor: "Editor",
        visualization: "Visualisierung",
        zoom_controls: "Zoom-Steuerelemente",
        qrcode: "QR-Code",
        display: "Anzeige",
        description_list: "Beschreibungsliste",
        data: "Daten",
        user_guide: "Benutzerhandbuch",
    },
    pages: PageKeys {
        home: "Startseite",
        components: "Komponenten",
        system: "System",
        demos: "Demos",
        animations: "Animationen",
        interactive: "Interaktiv",
        design_system: "Designsystem",
        color_palette: "Farbpalette",
        css_utilities: "CSS-Werkzeuge",
        icons: "Symbole",
        i18n: "i18n",
        not_found: "Seite nicht gefunden",
    },
    labels: LabelKeys {
        explore_components: "Komponenten erkunden",
        layer_base: "Ebene 1 \u{2014} Basiskomponenten",
        layer_composed: "Ebene 2 \u{2014} Zusammengesetzte Komponenten",
        layer_complex: "Ebene 3 \u{2014} Komplexe Komponenten",
        overview: "Übersicht",
        complete: "Abgeschlossen",
        code: "Code",
        language: "Sprache",
        status: "Status",
        submit: "Absenden",
        cancel: "Abbrechen",
        confirm: "Bestätigen",
        close: "Schließen",
        search_placeholder: "Suchen...",
        loading: "Laden...",
        no_data: "Keine Daten",
    },
    descriptions: DescriptionKeys {
        button: "Primäre Auslöser mit Varianten: primär, sekundär, Gefahr, Geist.",
        input: "Texteingabefeld mit Validierungsstatus und Platzhalter-Unterstützung.",
        card: "Container zum Gruppieren verwandter Inhalte mit optionalem Kopf- und Fußzeile.",
        switch: "Boolesches Schaltsteuerelement.",
        avatar: "Benutzerdarstellung mit Bild und Initialen-Fallback.",
        tag: "Kompaktes Etikett zur Kategorisierung oder Statusanzeige.",
        search: "Sucheingabe mit sofortiger Filterung.",
        navigation: "Registerkarten, Breadcrumbs, Schritte und Menükomponenten.",
        form: "Formulargenerator mit Validierung, Layout und Übermittlungsverarbeitung.",
        feedback: "Toast-Benachrichtigungen, Warnungen, Fortschrittsbalken und Spinner.",
        cascader: "Hierarchischer Mehrstufen-Wähler.",
        transfer: "Doppelfeld-Übertragungs-Widget zum Verschieben von Elementen zwischen Listen.",
        collapsible: "Akkordeon/Einklapp-Panels mit Animation.",
        timeline: "Chronologische Ereignisanzeige.",
        tree: "Hierarchische Baumansicht mit Auf-/Zuklappen.",
        pagination: "Seitennavigationssteuerung.",
        media_player: "Video- und Audio-Player mit benutzerdefinierten Steuerelementen.",
        editor: "Rich-Text- und Markdown-Editor mit Formatierungswerkzeugleiste.",
        visualization: "Diagramme, Grafiken und Datenvisualisierungs-Primitive.",
        zoom_controls: "Vergrößerungs-, Verkleinerungs- und Zurücksetzungssteuerungen.",
    },
};

static KEYS_ES: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "Botón",
        input: "Entrada",
        card: "Tarjeta",
        menu: "Menú",
        switch: "Interruptor",
        avatar: "Avatar",
        tag: "Etiqueta",
        image: "Imagen",
        empty: "Vacío",
        comment: "Comentario",
        search: "Búsqueda",
        number_input: "Entrada numérica",
        navigation: "Navegación",
        table: "Tabla",
        form: "Formulario",
        feedback: "Retroalimentación",
        cascader: "Cascada",
        transfer: "Transferencia",
        collapsible: "Colapsable",
        timeline: "Línea de tiempo",
        tree: "Árbol",
        pagination: "Paginación",
        media_player: "Reproductor multimedia",
        editor: "Editor",
        visualization: "Visualización",
        zoom_controls: "Controles de zoom",
        qrcode: "Código QR",
        display: "Visualización",
        description_list: "Lista de descripción",
        data: "Datos",
        user_guide: "Guía de usuario",
    },
    pages: PageKeys {
        home: "Inicio",
        components: "Componentes",
        system: "Sistema",
        demos: "Demos",
        animations: "Animaciones",
        interactive: "Interactivo",
        design_system: "Sistema de diseño",
        color_palette: "Paleta de colores",
        css_utilities: "Utilidades CSS",
        icons: "Iconos",
        i18n: "i18n",
        not_found: "Página no encontrada",
    },
    labels: LabelKeys {
        explore_components: "Explorar componentes",
        layer_base: "Capa 1 \u{2014} Componentes base",
        layer_composed: "Capa 2 \u{2014} Componentes compuestos",
        layer_complex: "Capa 3 \u{2014} Componentes complejos",
        overview: "Resumen",
        complete: "Completo",
        code: "Código",
        language: "Idioma",
        status: "Estado",
        submit: "Enviar",
        cancel: "Cancelar",
        confirm: "Confirmar",
        close: "Cerrar",
        search_placeholder: "Buscar...",
        loading: "Cargando...",
        no_data: "Sin datos",
    },
    descriptions: DescriptionKeys {
        button: "Desencadenador de acción principal con variantes: primario, secundario, peligro, fantasma.",
        input: "Campo de entrada de texto con estados de validación y soporte de marcador de posición.",
        card: "Contenedor para agrupar contenido relacionado con encabezado y pie de página opcionales.",
        switch: "Control de alternancia booleano.",
        avatar: "Representación de usuario con imagen y respaldo de iniciales.",
        tag: "Etiqueta compacta para categorización o visualización de estado.",
        search: "Entrada de búsqueda con filtrado instantáneo.",
        navigation: "Pestañas, breadcrumbs, pasos y componentes de menú.",
        form: "Constructor de formularios con validación, diseño y manejo de envío.",
        feedback: "Notificaciones toast, alertas, barras de progreso e indicadores de carga.",
        cascader: "Selector multinivel jerárquico.",
        transfer: "Widget de transferencia de panel doble para mover elementos entre listas.",
        collapsible: "Paneles acordeón/colapsables con animación.",
        timeline: "Visualización cronológica de eventos.",
        tree: "Vista de árbol jerárquica con expandir/contraer.",
        pagination: "Control de navegación de página.",
        media_player: "Reproductor de video y audio con controles personalizados.",
        editor: "Editor de texto enriquecido y Markdown con barra de herramientas de formato.",
        visualization: "Gráficos y primitivas de visualización de datos.",
        zoom_controls: "Controles de acercamiento, alejamiento y restablecimiento.",
    },
};

static KEYS_AR: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "زر",
        input: "حقل إدخال",
        card: "بطاقة",
        menu: "قائمة",
        switch: "مفتاح تبديل",
        avatar: "صورة رمزية",
        tag: "وسم",
        image: "صورة",
        empty: "فارغ",
        comment: "تعليق",
        search: "بحث",
        number_input: "إدخال رقمي",
        navigation: "التنقل",
        table: "جدول",
        form: "نموذج",
        feedback: "التعليقات",
        cascader: "محدد متتالي",
        transfer: "نقل",
        collapsible: "قابل للطي",
        timeline: "الجدول الزمني",
        tree: "شجرة",
        pagination: "ترقيم الصفحات",
        media_player: "مشغل الوسائط",
        editor: "محرر",
        visualization: "التصور",
        zoom_controls: "عناصر التحكم بالتكبير",
        qrcode: "رمز QR",
        display: "عرض",
        description_list: "قائمة الوصف",
        data: "بيانات",
        user_guide: "دليل المستخدم",
    },
    pages: PageKeys {
        home: "الرئيسية",
        components: "المكونات",
        system: "النظام",
        demos: "عروض",
        animations: "الرسوم المتحركة",
        interactive: "تفاعلي",
        design_system: "نظام التصميم",
        color_palette: "لوحة الألوان",
        css_utilities: "أدوات CSS",
        icons: "الأيقونات",
        i18n: "التدويل",
        not_found: "الصفحة غير موجودة",
    },
    labels: LabelKeys {
        explore_components: "استكشاف المكونات",
        layer_base: "الطبقة 1 \u{2014} مكونات أساسية",
        layer_composed: "الطبقة 2 \u{2014} مكونات مركبة",
        layer_complex: "الطبقة 3 \u{2014} مكونات معقدة",
        overview: "نظرة عامة",
        complete: "مكتمل",
        code: "الكود",
        language: "اللغة",
        status: "الحالة",
        submit: "إرسال",
        cancel: "إلغاء",
        confirm: "تأكيد",
        close: "إغلاق",
        search_placeholder: "بحث...",
        loading: "جارٍ التحميل...",
        no_data: "لا توجد بيانات",
    },
    descriptions: DescriptionKeys {
        button: "زر الإجراء الأساسي مع أشكال: أساسي، ثانوي، خطر، شبح.",
        input: "حقل إدخال نصي مع حالات التحقق ودعم العنصر النائب.",
        card: "حاوية لتجميع المحتوى ذي الصلة مع رأس وتذييل اختياريين.",
        switch: "عنصر تحكم تبديل منطقي.",
        avatar: "تمثيل المستخدم مع صورة وبديل الأحرف الأولى.",
        tag: "ملصق مضغوط للتصنيف أو عرض الحالة.",
        search: "إدخال بحث مع تصفية فورية.",
        navigation: "علامات التبويب، مسارات التنقل، الخطوات ومكونات القائمة.",
        form: "منشئ نماذج مع التحقق والتخطيط ومعالجة الإرسال.",
        feedback: "إشعارات التنبيه، التنبيهات، أشرطة التقدم والمؤشرات.",
        cascader: "محدد متعدد المستويات هرمي.",
        transfer: "واجهة نقل مزدوجة لنقل العناصر بين القوائم.",
        collapsible: "لوحات أكورديون/قابلة للطي مع رسوم متحركة.",
        timeline: "عرض الأحداث الزمني.",
        tree: "عرض شجري هرمي مع توسيع/طي.",
        pagination: "عنصر تحكم التنقل بين الصفحات.",
        media_player: "مشغل فيديو وصوت مع عناصر تحكم مخصصة.",
        editor: "محرر نصوص غني وMarkdown مع شريط أدوات التنسيق.",
        visualization: "الرسوم البيانية وعناصر تصور البيانات.",
        zoom_controls: "عناصر التحكم بالتكبير والتصغير وإعادة التعيين.",
    },
};

static KEYS_RU: I18nKeys = I18nKeys {
    components: ComponentKeys {
        button: "Кнопка",
        input: "Поле ввода",
        card: "Карточка",
        menu: "Меню",
        switch: "Переключатель",
        avatar: "Аватар",
        tag: "Метка",
        image: "Изображение",
        empty: "Пусто",
        comment: "Комментарий",
        search: "Поиск",
        number_input: "Числовое поле",
        navigation: "Навигация",
        table: "Таблица",
        form: "Форма",
        feedback: "Обратная связь",
        cascader: "Каскад",
        transfer: "Перенос",
        collapsible: "Сворачиваемый",
        timeline: "Шкала времени",
        tree: "Дерево",
        pagination: "Пагинация",
        media_player: "Медиаплеер",
        editor: "Редактор",
        visualization: "Визуализация",
        zoom_controls: "Элементы масштабирования",
        qrcode: "QR-код",
        display: "Отображение",
        description_list: "Список описаний",
        data: "Данные",
        user_guide: "Руководство пользователя",
    },
    pages: PageKeys {
        home: "Главная",
        components: "Компоненты",
        system: "Система",
        demos: "Демо",
        animations: "Анимации",
        interactive: "Интерактив",
        design_system: "Система дизайна",
        color_palette: "Палитра цветов",
        css_utilities: "CSS утилиты",
        icons: "Иконки",
        i18n: "i18n",
        not_found: "Страница не найдена",
    },
    labels: LabelKeys {
        explore_components: "Исследовать компоненты",
        layer_base: "Слой 1 \u{2014} Базовые компоненты",
        layer_composed: "Слой 2 \u{2014} Составные компоненты",
        layer_complex: "Слой 3 \u{2014} Сложные компоненты",
        overview: "Обзор",
        complete: "Завершено",
        code: "Код",
        language: "Язык",
        status: "Статус",
        submit: "Отправить",
        cancel: "Отмена",
        confirm: "Подтвердить",
        close: "Закрыть",
        search_placeholder: "Поиск...",
        loading: "Загрузка...",
        no_data: "Нет данных",
    },
    descriptions: DescriptionKeys {
        button: "Кнопка основного действия с вариантами: основной, вторичный, опасный, призрачный.",
        input: "Текстовое поле ввода с состояниями валидации и поддержкой плейсхолдера.",
        card: "Контейнер для группировки связанного контента с опциональным верхом и низом.",
        switch: "Логический переключатель.",
        avatar: "Представление пользователя с изображением и запасными инициалами.",
        tag: "Компактная метка для категоризации или отображения статуса.",
        search: "Поле поиска с мгновенной фильтрацией.",
        navigation: "Вкладки, хлебные крошки, шаги и компоненты меню.",
        form: "Конструктор форм с валидацией, макетом и обработкой отправки.",
        feedback: "Всплывающие уведомления, предупреждения, прогресс-бары и спиннеры.",
        cascader: "Иерархический многоуровневый выборщик.",
        transfer: "Виджет переноса с двумя панелями для перемещения элементов между списками.",
        collapsible: "Панели аккордеона/сворачивания с анимацией.",
        timeline: "Хронологическое отображение событий.",
        tree: "Иерархическое древовидное представление с разворачиванием/сворачиванием.",
        pagination: "Управление навигацией по страницам.",
        media_player: "Видео- и аудиоплеер с пользовательскими элементами управления.",
        editor: "Редактор форматированного текста и Markdown с панелью инструментов.",
        visualization: "Диаграммы, графики и примитивы визуализации данных.",
        zoom_controls: "Управление масштабированием, уменьшением и сбросом.",
    },
};

pub fn detect_language() -> Language {
    #[cfg(target_arch = "wasm32")]
    {
        let href = tairitsu_web::wit_platform::wasm_impl::bindings::tairitsu_browser::full::location::get_href();

        if let Some(query_start) = href.find('?') {
            let query = &href[query_start + 1..];
            for pair in query.split('&') {
                if let Some(eq_pos) = pair.find('=') {
                    let key = &pair[..eq_pos];
                    let val = &pair[eq_pos + 1..];
                    if key == "lang" {
                        if let Some(lang) = Language::from_code(val) {
                            return lang;
                        }
                    }
                }
            }
        }

        if href.starts_with("#lang=") || href.contains("#lang=") {
            if let Some(hash_start) = href.find('#') {
                let hash = &href[hash_start..];
                if hash.starts_with("#lang=") {
                    let code = &hash[6..];
                    if let Some(lang) = Language::from_code(code) {
                        return lang;
                    }
                }
            }
        }

        let hash = tairitsu_web::wit_platform::wasm_impl::bindings::tairitsu_browser::full::location::get_hash();
        if hash.starts_with("#lang=") {
            let code = &hash[6..];
            if let Some(lang) = Language::from_code(code) {
                return lang;
            }
        }
    }

    Language::default_lang()
}

pub fn use_language() -> Language {
    detect_language()
}

pub fn supported_languages() -> &'static [(Language, &'static str)] {
    static LANGS: LazyLock<Vec<(Language, &'static str)>> = LazyLock::new(|| {
        vec![
            (Language::ENGLISH, "English"),
            (Language::CHINESE_SIMPLIFIED, "简体中文"),
            (Language::CHINESE_TRADITIONAL, "繁體中文"),
            (Language::JAPANESE, "日本語"),
            (Language::KOREAN, "한국어"),
            (Language::FRENCH, "Français"),
            (Language::from_code("de").unwrap_or(Language::ENGLISH), "Deutsch"),
            (Language::SPANISH, "Español"),
            (Language::ARABIC, "العربية"),
            (Language::RUSSIAN, "Русский"),
        ]
    });
    LANGS.as_slice()
}
