[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-router"
version = "0.1.0"

[dependencies]
hikari-database = {path = "../database", version = "^0"}
hikari-web = {path = "../web", version = "^0"}

anyhow = "^1"
axum = {version = "^0.6", features = ["query"]}
base64 = "^0.21"
chrono = "^0.4"
clap = {version = "^3", features = ["derive"]}
env_logger = "^0.10"
futures = {version = "^0.3", features = ["std"], default-features = false}
hyper = {version = "^0.14", features = ["server", "http1"]}
log = "^0.4"
serde = {version = "^1", features = ["derive"]}
serde_json = "^1"
stylist = {version = "^0.12", features = ["yew_integration", "ssr"]}
tokio = {version = "^1", features = ["macros"]}
tower = {version = "^0.4", features = ["make"]}
tracing = "^0.1"
tracing-subscriber = "^0.3"
url = "^2"
yew = {version = "^0.20", features = ["ssr", "hydration"]}

[dev-dependencies.web-sys]
features = [
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "HtmlHeadElement",
  "HtmlStyleElement",
  "CssStyleDeclaration",
]
version = "0.3"

[dependencies.tower-http]
features = ["fs", "trace", "compression-gzip"]
version = "^0.3"
