[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-web"
version = "0.1.0"

[dependencies]
gloo = "0.8"
serde = {version = "1", features = ["derive"]}
serde_derive = "1"
strum = "0.24"
strum_macros = "0.24"
wasm-logger = "0.2"
yew = {version = "0.20", features = ["hydration"]}
yew-router = "0.17"

[dependencies.web-sys]
features = [
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "HtmlHeadElement",
  "HtmlStyleElement",
  "CssStyleDeclaration",
]
version = "0.3"

[dependencies.stylist]
branch = "ssr-first-pass"
features = ["yew_integration", "ssr", "hydration"]
git = "https://github.com/futursolo/stylist-rs"
version = "*"
