[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-web"
version = "0.1.0"

[features]
default = []
web_env = ["yew/hydration", "stylist/hydration"]

[dependencies]
gloo = "^0.8"
serde = {version = "^1", features = ["derive"]}
serde_derive = "^1"
serde_json = "^1"
strum = "^0.24"
strum_macros = "^0.24"
stylist = {version = "^0.12", features = ["yew_integration", "hydration"]}
wasm-bindgen-futures = "^0.4"
wasm-logger = "^0.2"
yew = {version = "^0.20", features = ["csr"]}
yew-router = "^0.17"

[dependencies.web-sys]
features = [
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "HtmlHeadElement",
  "HtmlStyleElement",
  "CssStyleDeclaration",
]
version = "^0.3"
