#!/usr/bin/env python3
"""Generate src/generated/mdi_data.rs from icons/mdi/*.svg files.

This script reads SVG files from the workspace's icons/mdi/ directory
(which must be populated first via `just fetch-icons`) and generates
a Rust source file containing inline icon path data.

The generated file is committed to git so that hikari-icons works
as a git dependency without requiring a local icon fetch step.

Usage:
    python3 scripts/icons/generate_mdi_data.py
    python3 scripts/icons/generate_mdi_data.py --icons-dir /path/to/icons/mdi
"""
from __future__ import annotations

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_ICONS_DIR = WORKSPACE_ROOT / "icons" / "mdi"
DEFAULT_OUTPUT = WORKSPACE_ROOT / "packages" / "icons" / "src" / "generated" / "mdi_data.rs"
MDI_MINIMAL_PATH = WORKSPACE_ROOT / "packages" / "icons" / "src" / "mdi_minimal.rs"


def parse_icon_names(mdi_minimal_path: Path) -> dict[str, str]:
    """Parse MdiIcon enum variant -> kebab-case name from mdi_minimal.rs Display impl."""
    variants: dict[str, str] = {}
    in_display = False

    for line in mdi_minimal_path.read_text().splitlines():
        stripped = line.strip()
        if "impl std::fmt::Display for MdiIcon" in stripped:
            in_display = True
            continue
        if in_display:
            if stripped == "}" and "=>" not in stripped:
                in_display = False
                continue
            if "=>" in stripped and "write!" in stripped:
                variant = stripped.split("::")[1].split(" ")[0] if "::" in stripped else ""
                name_start = stripped.find('write!(f, "') + len('write!(f, "')
                name_end = stripped.find('")', name_start)
                kebab_name = stripped[name_start:name_end]
                if variant and kebab_name:
                    variants[variant] = kebab_name

    return variants


def parse_svg(svg_path: Path) -> tuple[str, str | None]:
    """Parse SVG file, return (viewBox, path_d)."""
    tree = ET.parse(str(svg_path))
    root = tree.getroot()
    view_box = root.get("viewBox", "0 0 24 24")
    path_el = root.find(".//{http://www.w3.org/2000/svg}path")
    path_d = path_el.get("d") if path_el is not None else None
    return view_box, path_d


def generate(variants: dict[str, str], icons_dir: Path, output: Path) -> None:
    """Generate the mdi_data.rs file."""
    output.parent.mkdir(parents=True, exist_ok=True)

    found = 0
    missing: list[str] = []
    const_lines: list[str] = []
    match_lines: list[str] = []

    for variant, kebab in sorted(variants.items()):
        svg_path = icons_dir / f"{kebab}.svg"
        if not svg_path.exists():
            missing.append(kebab)
            continue

        try:
            view_box, path_d = parse_svg(svg_path)
            if path_d is None:
                missing.append(kebab)
                continue

            const_name = variant.upper()
            const_lines.append(f"    pub const {const_name}: IconData = IconData {{")
            const_lines.append(f'        view_box: Some("{view_box}"),')
            const_lines.append(f'        width: Some("24"),')
            const_lines.append(f'        height: Some("24"),')
            const_lines.append(f'        path: Some("{path_d}"),')
            const_lines.append("        paths: &[],")
            const_lines.append("        elements: &[],")
            const_lines.append("    };")

            match_lines.append(f'        "{kebab}" => Some(&data::{const_name}),')
            found += 1
        except Exception as e:
            missing.append(f"{kebab} (parse error: {e})")

    lines = [
        "// Auto-generated by scripts/icons/generate_mdi_data.py",
        "// DO NOT EDIT - regenerate with: python3 scripts/icons/generate_mdi_data.py",
        f"// Generated from {found} MDI icons",
        "",
        "#![allow(dead_code)]",
        "",
        "#[derive(Copy, Clone, Debug)]",
        "pub struct PathData {",
        "    pub d: Option<&'static str>,",
        "    pub fill: Option<&'static str>,",
        "    pub stroke: Option<&'static str>,",
        "    pub stroke_width: Option<&'static str>,",
        "    pub stroke_linecap: Option<&'static str>,",
        "    pub stroke_linejoin: Option<&'static str>,",
        "    pub transform: Option<&'static str>,",
        "}",
        "",
        "#[derive(Copy, Clone, Debug)]",
        "pub struct SvgElem {",
        "    pub tag: &'static str,",
        "    pub attributes: &'static [(&'static str, &'static str)],",
        "}",
        "",
        "#[derive(Copy, Clone, Debug)]",
        "pub struct IconData {",
        "    pub view_box: Option<&'static str>,",
        "    pub width: Option<&'static str>,",
        "    pub height: Option<&'static str>,",
        "    pub path: Option<&'static str>,",
        "    pub paths: &'static [PathData],",
        "    pub elements: &'static [SvgElem],",
        "}",
        "",
        "pub mod data {",
        "    use super::IconData;",
        "",
        *const_lines,
        "}",
        "",
        "pub fn get(name: &str) -> Option<&'static IconData> {",
        "    match name {",
        *match_lines,
        '        _ => None,',
        "    }",
        "}",
        "",
    ]

    output.write_text("\n".join(lines))

    print(f"  Generated {output}")
    print(f"  Icons embedded: {found}")
    print(f"  Missing: {len(missing)}")
    if missing:
        for m in missing:
            print(f"    - {m}")
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate mdi_data.rs from SVG icons")
    parser.add_argument("--icons-dir", type=Path, default=DEFAULT_ICONS_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    variants = parse_icon_names(MDI_MINIMAL_PATH)
    print(f"  Found {len(variants)} icon variants in mdi_minimal.rs")
    generate(variants, args.icons_dir, args.output)


if __name__ == "__main__":
    main()
