[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-database"
version = "0.1.0"

[dependencies]
hikari-utils = { path = "../utils", version = "^0" }

anyhow = "^1"
chrono = { version = "^0.4", features = ["serde", "unstable-locales"] }
env_logger = "^0.10"
lazy_static = "*"
log = "^0.4"
strum = "^0.25"
strum_macros = "^0.25"
uuid = { version = "^1", features = [
  'v4',
  'fast-rng',
  'macro-diagnostics',
  'serde',
] }

sea-orm-migration = "^0.12"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", features = ["full"] }

[dependencies.sea-orm]
features = [
  "sqlx-mysql",
  "runtime-tokio-rustls",
  "with-uuid",
  "with-chrono",
  "with-json",
]
version = "^0.12"
