[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "hikari-macro-types"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

stylist = { workspace = true }
yew = { workspace = true }
yew-router = { workspace = true }
