use std::collections::{BTreeMap, BTreeSet};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let manifest_dir =
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by Cargo");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by Cargo");

    let workspace_root = env::var("CARGO_WORKSPACE_DIR").map_or_else(
        |_| {
            Path::new(&manifest_dir)
                .parent()
                .expect("palette package should be under workspace root")
                .to_path_buf()
        },
        PathBuf::from,
    );

    let scss_dirs = vec![
        workspace_root
            .join("components")
            .join("src")
            .join("styles")
            .join("components"),
        workspace_root.join("theme").join("styles"),
    ];

    let mut all_classes: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for scss_dir in &scss_dirs {
        if !scss_dir.exists() {
            continue;
        }
        collect_from_dir(scss_dir, &mut all_classes);
    }

    let classes_dir = Path::new(&out_dir).join("classes");
    fs::create_dir_all(&classes_dir)
        .expect("Failed to create output directory for generated classes");
    let dest = classes_dir.join("generated.rs");
    generate(&all_classes, &dest);

    println!(
        "cargo:warning=hikari-palette: {} component groups, {} classes generated",
        all_classes.len(),
        all_classes.values().map(Vec::len).sum::<usize>()
    );
}

fn collect_from_dir(dir: &Path, out: &mut BTreeMap<String, Vec<String>>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };

    let mut files: Vec<_> = entries
        .filter_map(Result::ok)
        .filter(|e| {
            e.path()
                .extension()
                .and_then(|s| s.to_str())
                .is_some_and(|s| s == "scss")
        })
        .filter(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            !name.starts_with('_') && !name.ends_with("-vars.scss")
        })
        .collect();
    files.sort_by_key(std::fs::DirEntry::file_name);

    for entry in files {
        let path = entry.path();
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();

        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };

        let group_name = stem.replace('-', "_");
        let prefix = format!("hi-{stem}-");
        let hikari_prefix = format!("hikari-{stem}-");

        let classes = extract_classes(&content, &prefix, &hikari_prefix);
        if classes.is_empty() {
            continue;
        }

        out.entry(group_name).or_default().extend(classes);
    }
}

fn extract_classes(scss: &str, prefix: &str, hikari_prefix: &str) -> Vec<String> {
    let mut seen = BTreeSet::new();
    let mut classes = Vec::new();
    let re = regex_lite::Regex::new(r"\.((?:hi-|hikari-)[a-zA-Z][a-zA-Z0-9_-]*)")
        .expect("regex pattern is statically validated");

    for line in scss.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("//") || trimmed.starts_with("/*") {
            continue;
        }

        for m in re.find_iter(trimmed) {
            let class = m.as_str()[1..].to_string();
            if !class.starts_with(prefix) && !class.starts_with(hikari_prefix) {
                continue;
            }
            if seen.insert(class.clone()) {
                classes.push(class);
            }
        }
    }

    classes
}

fn class_to_variant(class: &str) -> String {
    let stripped = class
        .strip_prefix("hi-")
        .or_else(|| class.strip_prefix("hikari-"))
        .unwrap_or(class);
    stripped
        .split('-')
        .filter(|p| !p.is_empty())
        .map(|part| {
            let mut c = part.chars();
            c.next().map_or_else(String::new, |first| {
                first.to_uppercase().to_string() + c.as_str()
            })
        })
        .collect()
}

fn generate(all_classes: &BTreeMap<String, Vec<String>>, dest: &Path) {
    let mut f = fs::File::create(dest).expect("Failed to create generated classes file");

    writeln!(
        f,
        "// @generated — DO NOT EDIT\n// Generated by hikari-palette build.rs from SCSS sources\n"
    )
    .expect("Failed to write generated file header");

    for (group, classes) in all_classes {
        let enum_name = to_pascal(group.as_str());

        let mut seen_variants = BTreeSet::new();
        let mut deduped = Vec::new();
        for class in classes {
            let variant = class_to_variant(class);
            if seen_variants.insert(variant.clone()) {
                deduped.push((variant, class));
            }
        }

        if deduped.is_empty() {
            continue;
        }

        writeln!(f, "/// Auto-generated from SCSS").expect("Failed to write enum doc comment");
        writeln!(f, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
            .expect("Failed to write derive macro");
        writeln!(f, "pub enum {enum_name} {{")
            .unwrap_or_else(|e| panic!("Failed to write enum declaration for {enum_name}: {e}"));

        for (variant, class) in &deduped {
            writeln!(f, "    /// `{class}`")
                .unwrap_or_else(|e| panic!("Failed to write variant {variant}: {e}"));
            writeln!(f, "    {variant},")
                .unwrap_or_else(|e| panic!("Failed to write variant {variant}: {e}"));
        }

        writeln!(f, "}}").unwrap_or_else(|e| panic!("Failed to close enum {enum_name}: {e}"));
        writeln!(f).expect("Failed to write blank line");

        writeln!(f, "impl tairitsu_style::TypedClass for {enum_name} {{")
            .unwrap_or_else(|e| panic!("Failed to write impl block for {enum_name}: {e}"));
        writeln!(f, "    fn class_name(&self) -> &'static str {{")
            .expect("Failed to write class_name fn");
        writeln!(f, "        match self {{").expect("Failed to write match");

        for (variant, class) in &deduped {
            writeln!(f, "            {enum_name}::{variant} => \"{class}\",").unwrap_or_else(|e| {
                panic!("Failed to write match arm {enum_name}::{variant}: {e}")
            });
        }

        writeln!(f, "        }}").expect("Failed to close match");
        writeln!(f, "    }}").expect("Failed to close class_name fn");
        writeln!(f, "}}").unwrap_or_else(|e| panic!("Failed to close impl for {enum_name}: {e}"));
        writeln!(f).expect("Failed to write blank line");
    }
}

fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}
