use std::collections::{BTreeMap, BTreeSet};
use std::io::Write;
use std::path::Path;
use std::{env, fs};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    let scss_dirs = vec![
        Path::new(&manifest_dir)
            .parent()
            .unwrap()
            .join("components")
            .join("src")
            .join("styles")
            .join("components"),
        Path::new(&manifest_dir)
            .parent()
            .unwrap()
            .join("theme")
            .join("styles"),
    ];

    let mut all_classes: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for scss_dir in &scss_dirs {
        if !scss_dir.exists() {
            continue;
        }
        collect_from_dir(scss_dir, &mut all_classes);
    }

    let dest = Path::new(&out_dir).join("classes_generated.rs");
    generate(&all_classes, &dest);

    eprintln!(
        "hikari-palette: {} component groups, {} classes generated from SCSS",
        all_classes.len(),
        all_classes.values().map(|v| v.len()).sum::<usize>()
    );
}

fn collect_from_dir(dir: &Path, out: &mut BTreeMap<String, Vec<String>>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    let mut files: Vec<_> = entries
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .and_then(|s| s.to_str())
                .map(|s| s == "scss")
                .unwrap_or(false)
        })
        .filter(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            !name.starts_with('_') && !name.ends_with("-vars.scss")
        })
        .collect();
    files.sort_by_key(|e| e.file_name());

    for entry in files {
        let path = entry.path();
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();

        let content = match fs::read_to_string(&path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let group_name = stem.replace('-', "_");
        let prefix = format!("hi-{}-", stem);
        let hikari_prefix = format!("hikari-{}-", stem);

        let classes = extract_classes(&content, &prefix, &hikari_prefix);
        if classes.is_empty() {
            continue;
        }

        out.entry(group_name).or_default().extend(classes);
    }
}

fn extract_classes(scss: &str, prefix: &str, hikari_prefix: &str) -> Vec<String> {
    let mut seen = BTreeSet::new();
    let mut classes = Vec::new();

    for line in scss.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("//") || trimmed.starts_with("/*") {
            continue;
        }

        for m in regex_lite::Regex::new(r"\.((?:hi-|hikari-)[a-zA-Z][a-zA-Z0-9_-]*)")
            .unwrap()
            .find_iter(trimmed)
        {
            let class = m.as_str()[1..].to_string();
            if !class.starts_with(prefix) && !class.starts_with(hikari_prefix) {
                continue;
            }
            if seen.insert(class.clone()) {
                classes.push(class);
            }
        }
    }

    classes
}

fn class_to_variant(class: &str) -> String {
    let stripped = class
        .strip_prefix("hi-")
        .or_else(|| class.strip_prefix("hikari-"))
        .unwrap_or(class);
    stripped
        .split('-')
        .filter(|p| !p.is_empty())
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}

fn generate(all_classes: &BTreeMap<String, Vec<String>>, dest: &Path) {
    let mut f = fs::File::create(dest).unwrap();

    writeln!(
        f,
        "// @generated — DO NOT EDIT\n// Generated by hikari-palette build.rs from SCSS sources\n"
    )
    .unwrap();

    for (group, classes) in all_classes {
        let enum_name = to_pascal(group.as_str());

        let mut seen_variants = BTreeSet::new();
        let mut deduped = Vec::new();
        for class in classes {
            let variant = class_to_variant(class);
            if seen_variants.insert(variant.clone()) {
                deduped.push((variant, class));
            }
        }

        if deduped.is_empty() {
            continue;
        }

        writeln!(f, "/// Auto-generated from SCSS").unwrap();
        writeln!(f, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
        writeln!(f, "pub enum {} {{", enum_name).unwrap();

        for (variant, class) in &deduped {
            writeln!(f, "    /// `{}`", class).unwrap();
            writeln!(f, "    {},", variant).unwrap();
        }

        writeln!(f, "}}").unwrap();
        writeln!(f).unwrap();

        writeln!(f, "impl tairitsu_style::TypedClass for {} {{", enum_name).unwrap();
        writeln!(f, "    fn class_name(&self) -> &'static str {{").unwrap();
        writeln!(f, "        match self {{").unwrap();

        for (variant, class) in &deduped {
            writeln!(
                f,
                "            {}::{} => \"{}\",",
                enum_name, variant, class
            )
            .unwrap();
        }

        writeln!(f, "        }}").unwrap();
        writeln!(f, "    }}").unwrap();
        writeln!(f, "}}").unwrap();
        writeln!(f).unwrap();
    }
}

fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}
