#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hikari Tailwind CSS Fetcher

Downloads the Tailwind CSS CDN bundle and generates a Rust module
with the CSS as a static string constant for embedding.

Output: packages/theme/src/generated/tailwind.rs
"""

import urllib.request
from pathlib import Path
from datetime import datetime

# Tailwind CSS CDN URL (use direct CSS file instead of JS bundle)
TAILWIND_CDN_URL = "https://unpkg.com/tailwindcss@3.4.1/tailwind.css"

# Output paths
OUTPUT_DIR = Path("packages/theme/src/generated")
OUTPUT_FILE = OUTPUT_DIR / "tailwind.rs"


def fetch_tailwind_css() -> str:
    """Fetch Tailwind CSS from CDN"""
    print(f"Fetching Tailwind CSS from CDN...")
    print(f"  URL: {TAILWIND_CDN_URL}")
    
    try:
        request = urllib.request.Request(
            TAILWIND_CDN_URL,
            headers={
                'User-Agent': 'Hikari-Tailwind-Fetcher/1.0',
                'Accept': 'text/css,*/*'
            }
        )
        with urllib.request.urlopen(request, timeout=30) as response:
            css_content = response.read().decode('utf-8')
            print(f"  OK: Downloaded {len(css_content)} bytes")
            return css_content
    except Exception as e:
        print(f"  ERROR: Failed to fetch Tailwind CSS: {e}")
        raise


def generate_rust_module(css_content: str) -> str:
    """Generate Rust module with CSS as static constant"""
    
    # Generate header
    output = []
    output.append("// Auto-generated by scripts/fetch_tailwindcss.py")
    output.append(f"// Generated at: {datetime.now().isoformat()}")
    output.append(f"// Source: {TAILWIND_CDN_URL}")
    output.append(f"// Size: {len(css_content)} bytes")
    output.append("")
    output.append("#![allow(dead_code)]")
    output.append("")
    output.append("/// Tailwind CSS utility classes")
    output.append("///")
    output.append("/// This module contains the full Tailwind CSS bundle downloaded from the CDN.")
    output.append("/// It provides all utility classes for rapid UI development.")
    output.append("///")
    output.append("/// See: https://tailwindcss.com/docs/utility-first")
    output.append("pub const TAILWIND_CSS: &str = r#\"")
    
    # Add CSS content
    output.append(css_content)
    
    # Close the raw string literal
    output.append("\"#;")
    
    return "\n".join(output)


def main():
    """Main generation workflow"""
    print("=" * 60)
    print("Hikari Tailwind CSS Fetcher")
    print("=" * 60)
    
    # Fetch CSS
    css_content = fetch_tailwind_css()
    
    # Generate Rust module
    print("\nGenerating Rust module...")
    rust_code = generate_rust_module(css_content)
    
    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Write to file
    print(f"Writing to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(rust_code)
    
    file_size = OUTPUT_FILE.stat().st_size
    print(f"  OK: Generated {OUTPUT_FILE} ({file_size} bytes)")
    
    # Print summary
    print("\n" + "=" * 60)
    print("SUCCESS!")
    print("=" * 60)
    print(f"Tailwind CSS size: {len(css_content)} bytes")
    print(f"Rust module size: {file_size} bytes")
    print(f"\nOutput file:")
    print(f"  - {OUTPUT_FILE}")
    print(f"\nRust usage:")
    print(f"  use hikari_theme::generated::tailwind::TAILWIND_CSS;")
    print(f"  let css = TAILWIND_CSS;")
    print("=" * 60)


if __name__ == "__main__":
    main()
