[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "hikari-components-data"

version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hikari-components-container = { path = "../components-container" }
hikari-theme = { path = "../theme" }

anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

stylist = { workspace = true }
yew = { workspace = true }
yew-router = { workspace = true }
