[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-app"
version = "0.1.0"

build = "src/build.rs"

[features]
default = []
devtools = []

[build-dependencies]
tauri-build = { version = "^1", features = [] }

[dependencies]
anyhow = "^1"
chrono = "^0.4"
env_logger = "^0.10"
log = "^0.4"
tauri = "^1"
tokio = { version = "^1", features = ["full"] }
