[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-router"
version = "0.1.0"

[dependencies]
hikari-database = {path = "../database", version = "^0"}
hikari-web = {path = "../../frontend/web", version = "^0"}

axum = {version = "^0.6", features = ["query"]}
clap = {version = "^3", features = ["derive"]}
env_logger = "^0.9"
futures = {version = "^0.3", features = ["std"], default-features = false}
hyper = {version = "^0.14", features = ["server", "http1"]}
tokio = {version = "^1", features = ["macros"]}
tower = {version = "^0.4", features = ["make"]}
tracing = "^0.1"
tracing-subscriber = "^0.3"
url = "^2"
yew = {version = "^0.20", features = ["csr", "ssr", "hydration"]}

[dev-dependencies.web-sys]
features = [
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "HtmlHeadElement",
  "HtmlStyleElement",
  "CssStyleDeclaration",
]
version = "0.3"

[dependencies.stylist]
branch = "ssr-first-pass"
features = ["yew_integration", "ssr", "hydration"]
git = "https://github.com/futursolo/stylist-rs"
version = "*"

[dependencies.tower-http]
features = ["fs", "trace", "compression-gzip"]
version = "^0.3"
