[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-router"
version = "0.1.0"

[dependencies]
salvo = "0.37"
tokio = {version = "1", features = ["macros"]}
tracing = "0.1"
tracing-subscriber = "0.3"
