// website/src/pages/system/mod.rs
// System showcase pages
// Auto-generated by scripts/generate_bulk_imports.py
//
// 批量导入策略：使用include!宏进行编译时导入
//

include!("animations.rs");
include!("css.rs");
include!("icons.rs");
include!("overview.rs");
include!("palette.rs");

// Re-export all

pub use animations::*;
pub use css::*;
pub use icons::*;
pub use overview::*;
pub use palette::*;
