/**
 * Source contract for the window-layer animation rules (2026-09-06 user
 * directive). Every modal-context surface's dim curtain — the
 * HkModal/HkDrawer overlay, the sheet scrim of HkSelectPanel and
 * HkPopover — is an INDEPENDENT full-screen layer that fades in and out
 * in place: opacity only, own transition name, never the panel's.
 *
 * The bug this pins shut: the HkSelectPanel sheet scrim reused the
 * panel's `hk-select-sheet` transition name, so the panel's
 * `translateY(100%)` enter pair applied to the backdrop too — on phones
 * every second-level dropdown sheet dragged its dim curtain up from the
 * bottom edge, while first-level modals (distinct overlay name) looked
 * right.
 *
 * The classes are GENERATED by the shared mixin (_scrim-fade.scss), so
 * this test compiles each surface stylesheet and pins the emitted css —
 * it holds no matter how a surface authors its rules, and fails the
 * moment a curtain regains a transform or a panel loses its slide.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as sass from "sass";

const here = dirname(fileURLToPath(import.meta.url));
const read = (f: string) => readFileSync(join(here, f), "utf-8");

const CURTAINS: Array<{ file: string; curtain: string }> = [
  { file: "HkModal.scss", curtain: "hk-modal-overlay" },
  { file: "HkDrawer.scss", curtain: "hk-drawer-overlay" },
  { file: "HkSelect.scss", curtain: "hk-select-sheet-scrim" },
  { file: "HkPopover.scss", curtain: "hk-popover-scrim" },
];

/** One compiled rule block for `<curtain>-<phase>`, or "" when absent. */
function rule(css: string, curtain: string, phase: string): string {
  return css.match(new RegExp(`\\.${curtain}-${phase}[^{]*\\{[^}]*\\}`))?.[0] ?? "";
}

describe("window-layer scrim fade contract", () => {
  for (const { file, curtain } of CURTAINS) {
    it(`${curtain} (${file}) fades in place — opacity only, no transform`, () => {
      const css = sass.compile(join(here, file)).css;
      for (const phase of ["enter-active", "leave-active"]) {
        const block = rule(css, curtain, phase);
        expect(block, `${curtain}-${phase} rule missing`).toContain("transition: opacity");
        expect(block, `${curtain}-${phase} must not move the curtain`).not.toContain("transform");
      }
      for (const phase of ["enter-from", "leave-to"]) {
        const block = rule(css, curtain, phase);
        expect(block, `${curtain}-${phase} rule missing`).toContain("opacity: 0");
        expect(block, `${curtain}-${phase} must not move the curtain`).not.toContain("transform");
      }
    });
  }

  it("the sheet PANELS keep their slide — the contract never flattens the panel", () => {
    const select = sass.compile(join(here, "HkSelect.scss")).css;
    expect(rule(select, "hk-select-sheet", "enter-from")).toContain("translateY(100%)");
    const popover = sass.compile(join(here, "HkPopover.scss")).css;
    expect(rule(popover, "hk-popover-sheet", "enter-from")).toContain("translateY(100%)");
  });

  it("the select sheet scrim rides a transition name distinct from the panel's", () => {
    const src = read("HkSelectPanel.tsx");
    const names = Array.from(src.matchAll(/<Transition name="([^"]+)"/g), (m) => m[1]);
    expect(names).toContain("hk-select-sheet-scrim");
    expect(names).toContain("hk-select-sheet");
    expect(src).toContain('sheetScrimAnim.hooks("scrim")');
  });

  it("the popover sheet scrim fades instead of mounting bare", () => {
    const src = read("HkPopover.tsx");
    expect(src).toContain('<Transition name="hk-popover-scrim"');
    expect(src).toContain('surfaceAnim.hooks("scrim")');
    // The panel's sheet name stays the slide family — distinct from the scrim.
    expect(src).toContain('"hk-popover-sheet"');
  });
});
