#!/usr/bin/env python3
"""
Generate Lucide Icons enum from Lucide GitHub repository

This script fetches the list of all Lucide icons from the official
GitHub repository and generates a Rust enum with all icon names.
"""

import requests
import json
from pathlib import Path
from datetime import datetime

# Lucide GitHub API
GITHUB_API = "https://api.github.com/repos/lucide-icons/lucide/contents/icons"
OUTPUT_FILE = "packages/icons/src/generated.rs"

# Rust reserved keywords that need to be escaped
RUST_KEYWORDS = {
    'box', 'match', 'if', 'else', 'while', 'for', 'loop', 'return',
    'fn', 'let', 'mut', 'const', 'static', 'struct', 'enum', 'impl',
    'use', 'mod', 'trait', 'type', 'where', 'in', 'true', 'false',
    'move', 'ref', 'unsafe', 'async', 'await', 'break', 'continue',
    'yield', 'try', 'crate', 'super', 'self', 'extern', 'pub',
}

def fetch_icons():
    """Fetch all icon names from Lucide GitHub API"""
    print(f"Fetching icons from GitHub...")
    try:
        # Fetch icons directory from GitHub
        response = requests.get(GITHUB_API, timeout=30, headers={
            'Accept': 'application/vnd.github.v3+json'
        })
        response.raise_for_status()
        data = response.json()

        # Extract icon names (remove .svg extension)
        icons = [item['name'].replace('.svg', '') for item in data if item['name'].endswith('.svg')]
        icons.sort()

        print(f"OK: Fetched {len(icons)} icons")
        return icons
    except Exception as e:
        print(f"ERROR: Failed to fetch icons: {e}")
        raise

def generate_enum(icons):
    """Generate Rust enum from icon names"""

    # Helper function to escape Rust keywords
    def escape_variant(icon_name):
        """Escape icon name if it's a Rust keyword"""
        # Convert kebab-case to snake_case
        variant_name = icon_name.replace('-', '_')
        # Escape if it's a reserved keyword
        if variant_name in RUST_KEYWORDS:
            return f"r#{variant_name}"
        return variant_name

    # Header
    output = []
    output.append("// Auto-generated by scripts/generate_lucide_icons.py")
    output.append(f"// Generated at: {datetime.now().isoformat()}")
    output.append(f"// Total icons: {len(icons)}")
    output.append("")
    output.append("#![allow(non_camel_case_types)]")
    output.append("#![allow(dead_code)]")
    output.append("")
    output.append("/// Lucide icon names")
    output.append("///")
    output.append("/// This enum contains all icons from the Lucide icon library.")
    output.append("/// See: https://lucide.dev/icons/")
    output.append("#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]")
    output.append("pub enum LucideIcon {")
    output.append("    #[doc(hidden)]")
    output.append("    Unknown,")

    # Enum variants
    for icon in icons:
        variant_name = escape_variant(icon)
        output.append(f"    {variant_name},")

    output.append("}")

    # Display implementation
    output.append("")
    output.append("impl std::fmt::Display for LucideIcon {")
    output.append("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
    output.append("        match self {")
    output.append("            LucideIcon::Unknown => write!(f, \"unknown\"),")

    for icon in icons:
        variant_name = escape_variant(icon)
        output.append(f"            LucideIcon::{variant_name} => write!(f, \"{icon}\"),")

    output.append("        }")
    output.append("    }")
    output.append("}")

    # From<&str> implementation
    output.append("")
    output.append("impl std::convert::From<&str> for LucideIcon {")
    output.append("    fn from(s: &str) -> Self {")
    output.append("        match s {")

    for icon in icons:
        variant_name = escape_variant(icon)
        output.append(f"            \"{icon}\" => LucideIcon::{variant_name},")

    output.append("            _ => LucideIcon::Unknown,")
    output.append("        }")
    output.append("    }")
    output.append("}")

    return "\n".join(output)

def main():
    """Main generation workflow"""
    print("=" * 60)
    print("Generating Lucide Icons Enum")
    print("=" * 60)

    # Fetch icons
    icons = fetch_icons()

    # Generate enum
    print("\nGenerating Rust enum...")
    rust_code = generate_enum(icons)

    # Write to file
    output_path = Path(OUTPUT_FILE)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(rust_code)

    print(f"OK: Generated {OUTPUT_FILE}")
    print(f"OK: Total icons: {len(icons)}")

    # Show some examples
    print("\nSample icons:")
    for icon in icons[:10]:
        print(f"  - {icon}")
    if len(icons) > 10:
        print(f"  ... and {len(icons) - 10} more")

    print("\nSUCCESS: Icon enum generated!")

if __name__ == "__main__":
    main()
