#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate bulk import mod.rs files for website project

This script scans directories and generates mod.rs files with include! macros
for compile-time imports instead of manual mod declarations.
"""

import os
from pathlib import Path
from typing import List, Dict


def scan_rust_files(directory: Path) -> List[Path]:
    """Scan a directory for .rs files, excluding mod.rs"""
    if not directory.exists():
        return []

    return [
        f for f in directory.glob("*.rs")
        if f.name != "mod.rs" and f.is_file()
    ]


def generate_mod_rs(directory: Path, category: str = None) -> str:
    """Generate mod.rs content with include! macros"""

    rust_files = sorted(scan_rust_files(directory))

    if not rust_files:
        return f"// No modules found in {directory.name}\n"

    lines = []
    lines.append(f"// website/src/{directory.relative_to('examples/website/src')}")
    lines.append(f"// Auto-generated by scripts/generate_bulk_imports.py")
    lines.append(f"//")
    lines.append(f"// 批量导入策略：使用include!宏进行编译时导入")
    lines.append(f"")
    lines.append(f"// {category or directory.name.title()} modules")
    lines.append(f"")

    # Generate include! statements
    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"include!(\"{module_name}.rs\");")

    lines.append(f"")
    lines.append(f"// Re-export all modules")
    lines.append(f"")

    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"pub use {module_name}::*;")

    return "\n".join(lines) + "\n"


def generate_components_mod_rs():
    """Generate components mod.rs"""

    components_dir = Path("examples/website/src/components")
    mod_file = components_dir / "mod.rs"

    content = """// website/src/components/mod.rs
// Demo-specific components
//
// 批量导入策略：使用include!宏进行编译时导入

// Layout components
include!("layout.rs");

// Navigation components
include!("sidebar.rs");
include!("sidebar_tree.rs");
include!("top_nav.rs");

// Re-export all components
pub use layout::*;
pub use sidebar::*;
pub use sidebar_tree::*;
pub use top_nav::*;
"""

    mod_file.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {mod_file}")


def generate_pages_mod_rs():
    """Generate pages mod.rs"""

    pages_dir = Path("examples/website/src/pages")
    mod_file = pages_dir / "mod.rs"

    rust_files = sorted(scan_rust_files(pages_dir))

    lines = []
    lines.append("// website/src/pages/mod.rs")
    lines.append("// Page modules")
    lines.append("// Auto-generated by scripts/generate_bulk_imports.py")
    lines.append("//")
    lines.append("// 批量导入策略：使用include!宏进行编译时导入")
    lines.append("//")
    lines.append("")

    # Generate include! statements
    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"include!(\"{module_name}/mod.rs\");")

    content = "\n".join(lines) + "\n"
    mod_file.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {mod_file}")


def generate_pages_components_mod_rs():
    """Generate pages/components mod.rs"""

    components_dir = Path("examples/website/src/pages/components")
    mod_file = components_dir / "mod.rs"

    rust_files = sorted(scan_rust_files(components_dir))

    lines = []
    lines.append("// website/src/pages/components/mod.rs")
    lines.append("// Component showcase pages")
    lines.append("// Auto-generated by scripts/generate_bulk_imports.py")
    lines.append("//")
    lines.append("// 批量导入策略：使用include!宏进行编译时导入")
    lines.append("//")
    lines.append("")

    # Generate include! statements
    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"include!(\"{module_name}.rs\");")

    lines.append("")
    lines.append("// Re-export all components")
    lines.append("")

    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"pub use {module_name}::*;")

    content = "\n".join(lines) + "\n"
    mod_file.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {mod_file}")


def generate_pages_system_mod_rs():
    """Generate pages/system mod.rs"""

    system_dir = Path("examples/website/src/pages/system")
    mod_file = system_dir / "mod.rs"

    rust_files = sorted(scan_rust_files(system_dir))

    lines = []
    lines.append("// website/src/pages/system/mod.rs")
    lines.append("// System showcase pages")
    lines.append("// Auto-generated by scripts/generate_bulk_imports.py")
    lines.append("//")
    lines.append("// 批量导入策略：使用include!宏进行编译时导入")
    lines.append("//")
    lines.append("")

    # Generate include! statements
    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"include!(\"{module_name}.rs\");")

    lines.append("")
    lines.append("// Re-export all")
    lines.append("")

    for rust_file in rust_files:
        module_name = rust_file.stem
        lines.append(f"pub use {module_name}::*;")

    content = "\n".join(lines) + "\n"
    mod_file.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {mod_file}")


def generate_pages_demos_mod_rs():
    """Generate pages/demos mod.rs"""

    demos_dir = Path("examples/website/src/pages/demos")
    mod_file = demos_dir / "mod.rs"

    rust_files = sorted(scan_rust_files(demos_dir))

    if not rust_files:
        # If no files, create minimal mod.rs
        content = """// website/src/pages/demos/mod.rs
// Demo pages
// Auto-generated by scripts/generate_bulk_imports.py

"""
    else:
        lines = []
        lines.append("// website/src/pages/demos/mod.rs")
        lines.append("// Demo pages")
        lines.append("// Auto-generated by scripts/generate_bulk_imports.py")
        lines.append("//")
        lines.append("// 批量导入策略：使用include!宏进行编译时导入")
        lines.append("//")
        lines.append("")

        # Generate include! statements
        for rust_file in rust_files:
            module_name = rust_file.stem
            lines.append(f"include!(\"{module_name}.rs\");")

        lines.append("")
        lines.append("// Re-export all")
        lines.append("")

        for rust_file in rust_files:
            module_name = rust_file.stem
            lines.append(f"pub use {module_name}::*;")

        content = "\n".join(lines) + "\n"

    mod_file.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {mod_file}")


def generate_all():
    """Generate all bulk import mod.rs files"""

    print("=" * 60)
    print("Generating bulk import mod.rs files for website")
    print("=" * 60)
    print()

    generate_components_mod_rs()
    generate_pages_mod_rs()
    generate_pages_components_mod_rs()
    generate_pages_system_mod_rs()
    generate_pages_demos_mod_rs()

    print()
    print("=" * 60)
    print("[OK] All bulk imports generated successfully!")
    print("=" * 60)


if __name__ == "__main__":
    generate_all()
