//! Button component classes

use tairitsu_style::TypedClass;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ButtonClass {
    Button,
    Primary,
    Secondary,
    Ghost,
    Borderless,
    Danger,
    Success,
    Sm,
    Md,
    Lg,
    Loading,
    Block,
    Spinner,
    Icon,
    SpaceBetween,
    WidthAuto,
    Width120,
    Width140,
    Width160,
    IconButton,
    IconButtonSize16,
    IconButtonSize24,
    IconButtonSize32,
    IconButtonSize36,
    IconButtonSize40,
    IconButtonGhost,
    IconButtonPrimary,
    IconButtonSecondary,
    IconButtonDanger,
    IconButtonSuccess,
    Disabled,
    IconButtonIcon,
    IconButtonDisabled,
    Suffix,
}

impl TypedClass for ButtonClass {
    fn class_name(&self) -> &'static str {
        match self {
            Self::Button => "hi-button",
            Self::Primary => "hi-button-primary",
            Self::Secondary => "hi-button-secondary",
            Self::Ghost => "hi-button-ghost",
            Self::Borderless => "hi-button-borderless",
            Self::Danger => "hi-button-danger",
            Self::Success => "hi-button-success",
            Self::Sm => "hi-button-sm",
            Self::Md => "hi-button-md",
            Self::Lg => "hi-button-lg",
            Self::Loading => "hi-button-loading",
            Self::Block => "hi-button-block",
            Self::Spinner => "hi-button-spinner",
            Self::Icon => "hi-button-icon",
            Self::SpaceBetween => "hi-button-space-between",
            Self::WidthAuto => "hi-button-width-auto",
            Self::Width120 => "hi-button-width-120",
            Self::Width140 => "hi-button-width-140",
            Self::Width160 => "hi-button-width-160",
            Self::IconButton => "hi-icon-button",
            Self::IconButtonSize16 => "hi-icon-button-16",
            Self::IconButtonSize24 => "hi-icon-button-24",
            Self::IconButtonSize32 => "hi-icon-button-32",
            Self::IconButtonSize36 => "hi-icon-button-36",
            Self::IconButtonSize40 => "hi-icon-button-40",
            Self::IconButtonGhost => "hi-icon-button-ghost",
            Self::IconButtonPrimary => "hi-icon-button-primary",
            Self::IconButtonSecondary => "hi-icon-button-secondary",
            Self::IconButtonDanger => "hi-icon-button-danger",
            Self::IconButtonSuccess => "hi-icon-button-success",
            Self::Disabled => "hi-button-disabled",
            Self::IconButtonIcon => "hi-icon-button-icon",
            Self::IconButtonDisabled => "hi-icon-button-disabled",
            Self::Suffix => "hi-button-suffix",
        }
    }
}
