//! Button component classes

use tairitsu_style::TypedClass;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ButtonClass {
    Button,
    Primary,
    Secondary,
    Ghost,
    Borderless,
    Danger,
    Success,
    Sm,
    Md,
    Lg,
    Loading,
    Block,
    Spinner,
    Icon,
    SpaceBetween,
    WidthAuto,
    Width120,
    Width140,
    Width160,
    IconButton,
    IconButtonSize16,
    IconButtonSize24,
    IconButtonSize32,
    IconButtonSize36,
    IconButtonSize40,
    IconButtonGhost,
    IconButtonPrimary,
    IconButtonSecondary,
    IconButtonDanger,
    IconButtonSuccess,
    Disabled,
    IconButtonIcon,
    IconButtonDisabled,
    Suffix,
}

impl TypedClass for ButtonClass {
    fn class_name(&self) -> &'static str {
        match self {
            ButtonClass::Button => "hi-button",
            ButtonClass::Primary => "hi-button-primary",
            ButtonClass::Secondary => "hi-button-secondary",
            ButtonClass::Ghost => "hi-button-ghost",
            ButtonClass::Borderless => "hi-button-borderless",
            ButtonClass::Danger => "hi-button-danger",
            ButtonClass::Success => "hi-button-success",
            ButtonClass::Sm => "hi-button-sm",
            ButtonClass::Md => "hi-button-md",
            ButtonClass::Lg => "hi-button-lg",
            ButtonClass::Loading => "hi-button-loading",
            ButtonClass::Block => "hi-button-block",
            ButtonClass::Spinner => "hi-button-spinner",
            ButtonClass::Icon => "hi-button-icon",
            ButtonClass::SpaceBetween => "hi-button-space-between",
            ButtonClass::WidthAuto => "hi-button-width-auto",
            ButtonClass::Width120 => "hi-button-width-120",
            ButtonClass::Width140 => "hi-button-width-140",
            ButtonClass::Width160 => "hi-button-width-160",
            ButtonClass::IconButton => "hi-icon-button",
            ButtonClass::IconButtonSize16 => "hi-icon-button-16",
            ButtonClass::IconButtonSize24 => "hi-icon-button-24",
            ButtonClass::IconButtonSize32 => "hi-icon-button-32",
            ButtonClass::IconButtonSize36 => "hi-icon-button-36",
            ButtonClass::IconButtonSize40 => "hi-icon-button-40",
            ButtonClass::IconButtonGhost => "hi-icon-button-ghost",
            ButtonClass::IconButtonPrimary => "hi-icon-button-primary",
            ButtonClass::IconButtonSecondary => "hi-icon-button-secondary",
            ButtonClass::IconButtonDanger => "hi-icon-button-danger",
            ButtonClass::IconButtonSuccess => "hi-icon-button-success",
            ButtonClass::Disabled => "hi-button-disabled",
            ButtonClass::IconButtonIcon => "hi-icon-button-icon",
            ButtonClass::IconButtonDisabled => "hi-icon-button-disabled",
            ButtonClass::Suffix => "hi-button-suffix",
        }
    }
}
