//! # Hikari Build System
//!
//! Build-time code generation and SCSS compilation for Hikari UI applications.
//!
//! ## Overview
//!
//! The Hikari build system automates several critical tasks during compilation:
//!
//! - **SCSS Compilation**: Uses [Grass](https://github.com/kaj/kaj) (Rust Sass compiler) to compile SCSS to CSS
//! - **Component Discovery**: Automatically discovers components from SCSS files
//! - **Code Generation**: Generates Rust constants for discovered components
//! - **Asset Bundling**: Creates optimized CSS bundles for production
//!
//! ## Architecture
//!
//! The build system is organized into several key components:
//!
//! - **[`build()`]** - Main entry point for the build process
//! - **[`BuildConfig`]** - Build configuration with component selection
//! - **[`Builder`]** - Fluent builder API for custom build configurations
//! - **Auto-generated constants** in `generated/components.rs`
//!
//! ## Usage in build.rs
//!
//! ### Basic Usage
//!
//! Add this to your `build.rs` file:
//!
//! ```rust,ignore
//! fn main() {
//!     hikari_builder::build().expect("Build failed");
//! }
//! ```
//!
//! ### With Custom Configuration
//!
//! ```rust,ignore
//! use hikari_builder::{Builder, BuildConfig};
//!
//! fn main() {
//!     let config = BuildConfig {
//!         components: vec![
//!             "button".to_string(),
//!             "input".to_string(),
//!             "card".to_string(),
//!         ],
//!         output_dir: "dist".into(),
//!         minify_css: true,
//!         ..BuildConfig::default()
//!     };
//!
//!     Builder::new(config)
//!         .build()
//!         .expect("Build failed");
//! }
//! ```
//!
//! ## Build Process
//!
//! When `cargo build` runs, the build system:
//!
//! 1. **Finds Workspace Root**
//!    - Traverses up from `CARGO_MANIFEST_DIR`
//!    - Locates `Cargo.toml` with `[workspace]` section
//!
//! 2. **Scans for SCSS Files**
//!    - Searches `packages/components/src/styles/components/`
//!    - Collects all `.scss` file names
//!    - Example: `button.scss` → component "button"
//!
//! 3. **Generates Rust Code**
//!    - Creates `packages/builder/src/generated/components.rs`
//!    - Exports `AVAILABLE_COMPONENTS: &[&str]`
//!    - Provides `default_components()` function
//!
//! 4. **Compiles SCSS Bundle**
//!    - Uses `packages/components/src/styles/index.scss` as entry point
//!    - Processes all `@import` and `@use` directives
//!    - Outputs to `public/styles/bundle.css`
//!    - Reports file size for optimization tracking
//!
//! ## SCSS Compilation
//!
//! The build system uses **Grass**, a pure-Rust Sass compiler:
//!
//! - **No Ruby dependency**: Fully compiled, faster than Ruby Sass
//! - **No external tools**: Everything runs in the build process
//! - **Full SCSS support**: Variables, mixins, functions, imports
//!
//! ### Entry Point Structure
//!
//! The main entry point (`packages/components/src/styles/index.scss`) should:
//!
//! ```scss
//! // Import component styles
//! @import 'components/button';
//! @import 'components/input';
//! @import 'components/card';
//!
//! // Import utility classes
//! @import 'utilities/display';
//! @import 'utilities/layout';
//!
//! // Import theme variables
//! @import 'variables';
//! ```
//!
//! ## Generated Code
//!
//! The build system generates `components.rs` with:
//!
//! ```rust,ignore
//! //! Auto-generated component list
//! //!
//! //! This file is generated by hikari-builder build script.
//! //! Do not edit manually.
//!
//! use std::collections::HashSet;
//!
//! /// List of available Hikari components
//! pub static AVAILABLE_COMPONENTS: &[&str] = &[
//!     "alert",
//!     "badge",
//!     "button",
//!     // ... more components
//! ];
//!
//! /// Get default set of components (all available)
//! pub fn default_components() -> HashSet<String> {
//!     AVAILABLE_COMPONENTS.iter().map(|s| s.to_string()).collect()
//! }
//! ```
//!
//! ## Build Configuration
//!
//! ### BuildConfig
//!
//! Customize the build process with [`BuildConfig`]:
//!
//! ```rust,ignore
//! use hikari_builder::BuildConfig;
//!
//! let config = BuildConfig {
//!     // Which components to include
//!     components: vec![
//!         "button".to_string(),
//!         "card".to_string(),
//!     ],
//!
//!     // Where to write output files
//!     output_dir: "public".into(),
//!
//!     // Project root directory
//!     project_root: ".".into(),
//!
//!     // Minify CSS for production
//!     minify_css: false,
//!
//!     // SCSS entry point
//!     scss_entry: "packages/components/src/styles/index.scss".into(),
//! };
//! ```
//!
//! ### Builder Pattern
//!
//! For advanced configuration, use the [`Builder`] API:
//!
//! ```rust,ignore
//! use hikari_builder::Builder;
//!
//! Builder::new(config)
//!     .build()
//!     .expect("Build failed");
//! ```
//!
//! ## Output Files
//!
//! The build system generates:
//!
//! | File | Description |
//! |------|-------------|
//! | `packages/builder/src/generated/components.rs` | Rust constants for components |
//! | `public/styles/bundle.css` | Compiled CSS bundle |
//! | `public/styles/` | Output directory for all CSS |
//!
//! ## Build Output
//!
//! During compilation, you'll see build progress:
//!
//! ```text
//! 🔨 Hikari Builder starting...
//! 📂 Workspace root: "/path/to/hikari"
//! 📄 Found 20 SCSS files
//! 📝 Generated components.rs
//! 🎨 Compiling SCSS with Grass...
//!    Entry point: "/path/to/hikari/packages/components/src/styles/index.scss"
//! ✅ CSS bundle generated: "/path/to/hikari/public/styles/bundle.css"
//!    Size: 45678 bytes
//! ✅ Hikari Builder completed!
//! ```
//!
//! ## Integration with Cargo
//!
//! The build system integrates seamlessly with Cargo's build process:
//!
//! 1. Runs automatically during `cargo build`
//! 2. Tracks SCSS file changes for rebuilds
//! 3. Outputs warnings for build progress
//! 4. Fails compilation if SCSS has errors
//!
//! ## Error Handling
//!
//! The build system returns detailed errors:
//!
//! ```rust,ignore
//! match hikari_builder::build() {
//!     Ok(_) => println!("Build successful"),
//!     Err(e) => eprintln!("Build failed: {}", e),
//! }
//! ```
//!
//! Common errors:
//!
//! - **`index.scss not found`**: Check SCSS entry point path
//! - **`SCSS compilation failed`**: Fix SCSS syntax errors
//! - **Invalid workspace root**: Ensure `[workspace]` in Cargo.toml
//!
//! ## Performance
//!
//! - **First build**: ~2-5 seconds (SCSS compilation)
//! - **Incremental builds**: <1 second (if SCSS unchanged)
//! - **Parallel builds**: Supported (one build per workspace member)
//!
//! ## Platform Support
//!
//! - **Linux**: ✅ Fully supported
//! - **macOS**: ✅ Fully supported
//! - **Windows**: ✅ Fully supported
//! - **WASM**: ✅ Can cross-compile for WASM target
//!
//! ## Icon Build System
//!
//! The icon build system provides on-demand icon selection and packaging:
//!
//! ```rust,ignore
//! use hikari_builder::icons::{build_icons, MdiStyle};
//!
//! build_icons()
//!     .names(["moon", "sun", "star"])
//!     .styles(vec![MdiStyle::Filled, MdiStyle::Outline])
//!     .build()?;
//! ```
//!
//! See [`icons`] module for more details.

pub mod icons;

use std::{
    env, fs,
    path::{Path, PathBuf},
};

/// Main build function - compiles SCSS and generates components
///
/// This is the primary entry point for the Hikari build system. It:
/// 1. Locates the workspace root
/// 2. Scans for SCSS component files
/// 3. Generates Rust constants for discovered components
/// 4. Compiles the SCSS bundle using Grass
///
/// # Errors
///
/// Returns an error if:
/// - Workspace root cannot be found
/// - SCSS files cannot be read
/// - Code generation fails
/// - SCSS compilation fails
///
/// # Example
///
/// ```rust,ignore
/// fn main() {
///     hikari_builder::build().expect("Build failed");
/// }
/// ```
pub fn build() -> anyhow::Result<()> {
    println!("🔨 Hikari Builder starting...");

    // Get workspace root
    let workspace_root = env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("."));

    // Find workspace root (go up until we find Cargo.toml with workspace members)
    let workspace_root = find_workspace_root(&workspace_root);

    println!("📂 Workspace root: {:?}", workspace_root);

    // Scan for SCSS files
    let scss_files = scan_scss_files(&workspace_root)?;
    println!("📄 Found {} SCSS files", scss_files.len());

    // Generate Rust constants
    let generated_dir = workspace_root.join("packages/builder/src/generated");
    fs::create_dir_all(&generated_dir)?;

    generate_component_constants(&generated_dir, &scss_files)?;

    // Compile SCSS bundle
    compile_scss_bundle(&workspace_root)?;

    println!("✅ Hikari Builder completed!");

    Ok(())
}

/// Find the workspace root by looking for Cargo.toml with [workspace]
fn find_workspace_root(start: &Path) -> PathBuf {
    let mut current = start;

    loop {
        let cargo_toml = current.join("Cargo.toml");
        if cargo_toml.exists()
            && let Ok(content) = fs::read_to_string(&cargo_toml)
            && content.contains("[workspace]")
        {
            return current.to_path_buf();
        }

        match current.parent() {
            Some(parent) if parent != current => {
                current = parent;
            }
            _ => return start.to_path_buf(),
        }
    }
}

/// Scan for all SCSS files in the project
fn scan_scss_files(workspace_root: &Path) -> anyhow::Result<Vec<String>> {
    let mut scss_files = Vec::new();

    // Scan packages/components/src/styles/components/
    let components_dir = workspace_root.join("packages/components/src/styles/components");
    if components_dir.exists() {
        let entries = fs::read_dir(&components_dir)?;
        for entry in entries {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("scss")
                && let Some(file_name) = path.file_stem().and_then(|s| s.to_str())
            {
                scss_files.push(file_name.to_string());
            }
        }
    }

    scss_files.sort();
    Ok(scss_files)
}

/// Generate Rust constants for discovered components
fn generate_component_constants(output_dir: &Path, components: &[String]) -> anyhow::Result<()> {
    let mut content = String::from(
        r#"//! Auto-generated component list
//!
//! This file is generated by hikari-builder build script.
//! Do not edit manually.

use std::collections::HashSet;

/// List of available Hikari components
pub static AVAILABLE_COMPONENTS: &[&str] = &[
"#,
    );

    for component in components {
        content.push_str(&format!("    \"{}\",\n", component));
    }

    content.push_str(
        r#"];

/// Get default set of components (all available)
pub fn default_components() -> HashSet<String> {
    AVAILABLE_COMPONENTS.iter().map(|s| s.to_string()).collect()
}
"#,
    );

    fs::write(output_dir.join("components.rs"), content)?;
    println!("📝 Generated components.rs");

    Ok(())
}

/// Compile SCSS to CSS bundle using Grass (Rust Sass compiler)
fn compile_scss_bundle(workspace_root: &Path) -> anyhow::Result<()> {
    println!("🎨 Compiling SCSS with Grass...");

    // Use index.scss as entry point (has @import for all components)
    let index_scss = workspace_root.join("packages/components/src/styles/index.scss");
    if !index_scss.exists() {
        return Err(anyhow::anyhow!("index.scss not found at {:?}", index_scss));
    }

    println!("   Entry point: {:?}", index_scss);

    // Compile with Grass - it will handle @import and @use resolution automatically
    let css_content = grass::from_path(&index_scss, &grass::Options::default())
        .map_err(|e| anyhow::anyhow!("SCSS compilation failed: {:?}", e))?;

    // Apply autoprefixer using lightningcss
    println!("🔄 Applying autoprefixer...");
    let stylesheet = lightningcss::stylesheet::StyleSheet::parse(&css_content, Default::default())
        .map_err(|e| anyhow::anyhow!("CSS parsing failed: {:?}", e))?;

    let prefixed_css = stylesheet
        .to_css(lightningcss::stylesheet::PrinterOptions {
            targets: lightningcss::targets::Targets::default(),
            ..Default::default()
        })
        .map_err(|e| anyhow::anyhow!("CSS autoprefixer failed: {:?}", e))?
        .code;

    // Get file size
    let file_size = prefixed_css.len();

    // Write to output directory
    let output_dir = workspace_root.join("public/styles");
    fs::create_dir_all(&output_dir)?;

    let css_output = output_dir.join("bundle.css");
    fs::write(&css_output, prefixed_css)?;

    println!("✅ CSS bundle generated: {:?}", css_output);
    println!("   Size: {} bytes", file_size);

    Ok(())
}

/// Build configuration
#[derive(Clone, Debug)]
pub struct BuildConfig {
    /// Enabled components (e.g., ["button", "badge", "card"])
    pub components: Vec<String>,

    /// Output directory (default: "public")
    pub output_dir: PathBuf,

    /// Project root directory (default: current directory)
    pub project_root: PathBuf,

    /// Whether to minify CSS (default: false)
    pub minify_css: bool,

    /// SCSS entry point (default: "packages/components/src/styles/index.scss")
    pub scss_entry: PathBuf,

    /// Whether to include i18n support (default: false)
    pub enable_i18n: bool,

    /// Supported languages (default: ["en-US", "zh-CN", "zh-TW"])
    pub languages: Vec<String>,

    /// i18n locales directory (default: "packages/i18n/locales")
    pub i18n_dir: PathBuf,
}

impl Default for BuildConfig {
    fn default() -> Self {
        Self {
            components: vec![
                "button".to_string(),
                "badge".to_string(),
                "card".to_string(),
                "input".to_string(),
                "alert".to_string(),
                "toast".to_string(),
                "tooltip".to_string(),
            ],
            output_dir: "public".into(),
            project_root: ".".into(),
            minify_css: false,
            scss_entry: "packages/components/src/styles/index.scss".into(),
            enable_i18n: false,
            languages: vec![
                "en-US".to_string(),
                "zh-CN".to_string(),
                "zh-TW".to_string(),
            ],
            i18n_dir: "packages/i18n/locales".into(),
        }
    }
}

/// Builder for Hikari UI applications
pub struct Builder {
    config: BuildConfig,
}

impl Builder {
    /// Create a new builder with the given configuration
    pub fn new(config: BuildConfig) -> anyhow::Result<Self> {
        Ok(Self { config })
    }

    /// Build the project
    pub fn build(&self) -> anyhow::Result<()> {
        // Ensure output directory exists
        std::fs::create_dir_all(&self.config.output_dir)?;

        // Note: SCSS compilation is handled by build.rs
        println!("✅ Build configuration prepared");

        Ok(())
    }
}
