[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "hikari-macro"

version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
hikari-macro-types = { path = "../macro-types" }

anyhow = "^1"
derive_more = "*"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
strum = { version = "^0.26", features = ["derive"] }

syn = { version = "^2", features = ["full"] }
proc-macro2 = "^1"
quote = "^1"
