[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "hikari-macro"

version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
hikari-macro-types = { path = "../macro-types" }

anyhow = { workspace = true }
derive_more = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

syn = { version = "^2", features = ["full"] }
proc-macro2 = "^1"
quote = "^1"
