[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "hikari-utils"
publish = false
version = "0.1.0"

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = "^1"
chrono = {version = "^0.4", features = ["serde", "wasmbind", "unstable-locales"]}
log = "^0.4"
serde = {version = "^1", features = ["derive"]}
serde_json = "^1"
strum = "^0.24"
strum_macros = "^0.24"
uuid = {version = "^1", features = ['v4', 'fast-rng', 'macro-diagnostics', 'serde']}

bcrypt = "^0.14"
