//! Build script for hikari-icons.
//!
//! Icon path data is now embedded directly in `src/generated/mdi_data.rs`
//! (generated by `scripts/icons/generate_mdi_data.py`), so this build
//! script no longer needs to read SVG files from the filesystem.
//!
//! To update icons:
//!   1. Run `just fetch-icons` to download SVGs to `icons/mdi/`
//!   2. Run `python3 scripts/icons/generate_mdi_data.py` to regenerate
//!   3. Commit the updated `src/generated/mdi_data.rs`

fn main() {
    let is_dynamic = std::env::var("CARGO_FEATURE_DYNAMIC_FETCH").is_ok();

    if is_dynamic {
        println!("cargo:rustc-env=HIKARI_ICON_ROUTE=/api/icons");
    } else {
        println!("cargo:rustc-env=HIKARI_ICON_ROUTE=/static/dynamic-icons");
    }

    println!("cargo:rerun-if-changed=src/generated/mdi_data.rs");
}
