//! Build script for hikari-icons.
//!
//! hikari-icons is a pure abstraction layer — it does not bundle icon data.
//! Instead, it expects `tairitsu-packager` to pre-generate a Rust source file
//! containing `impl_icons!(...)` macro invocations.
//!
//! Workflow:
//!   1. `tairitsu check --icons` downloads/caches icon data from CDN
//!   2. During `tairitsu build`, the packager generates the icon data file
//!      and sets `TAIRITSU_ICONS_RS` env var pointing to it
//!   3. This build script copies that file to `OUT_DIR` for `lib.rs` to `include!`
//!
//! To build without tairitsu-packager (e.g., for testing):
//!   1. Generate `impl_icons!` calls manually using the icons.txt manifest
//!   2. Place the file somewhere and set `TAIRITSU_ICONS_RS=<path>`
//!   3. Or run `cargo build` in a tairitsu-packager managed project

use std::env;
use std::fs;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    if env::var("CARGO_FEATURE_DYNAMIC_FETCH").is_ok() {
        println!("cargo:rustc-env=HIKARI_ICON_ROUTE=/api/icons");
    } else {
        println!("cargo:rustc-env=HIKARI_ICON_ROUTE=/static/dynamic-icons");
    }

    match env::var("TAIRITSU_ICONS_RS") {
        Ok(path) => {
            fs::copy(&path, format!("{}/mdi_generated.rs", out_dir)).unwrap_or_else(|e| {
                panic!(
                    "Failed to copy {} to OUT_DIR: {}. \
                     Ensure the file is readable.",
                    path, e
                )
            });
            println!("cargo:rerun-if-env-changed=TAIRITSU_ICONS_RS");
        }
        Err(_) => {
            panic!(
                "\n\
                 ╔══════════════════════════════════════════════════════════╗\n\
                 ║  hikari-icons: icon data not found                     ║\n\
                 ╠══════════════════════════════════════════════════════════╣\n\
                 ║                                                          ║\n\
                 ║  hikari-icons is a pure abstraction layer and does NOT   ║\n\
                 ║  bundle icon path data. It requires pre-built icon       ║\n\
                 ║  data generated by tairitsu-packager.                    ║\n\
                 ║                                                          ║\n\
                 ║  To resolve this:                                        ║\n\
                 ║    tairitsu check --icons                                ║\n\
                 ║    tairitsu check --icons --offline  (CI / offline)      ║\n\
                 ║                                                          ║\n\
                 ║  Or manually generate icon data and set:                 ║\n\
                 ║    TAIRITSU_ICONS_RS=<path-to-generated.rs>              ║\n\
                 ║                                                          ║\n\
                 ╚══════════════════════════════════════════════════════════╝\n\
            "
            );
        }
    }
}
