---
name: Run Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  rustfmt:
    name: Check Formatting
    runs-on: [self-hosted, linux, x64, local]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: sudo apt-get install -y libasound2-dev libudev-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Restore Rust Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Run cargo fmt -- --check
        run: cargo +nightly fmt --all -- --check --unstable-features

  lint:
    name: Lint
    runs-on: [self-hosted, linux, x64, local]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: sudo apt-get install -y libasound2-dev libudev-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-wasip2

      - name: Restore Rust Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Run cargo clippy
        run: cargo clippy --all --all-features
        env:
          RUSTFLAGS: '--cfg releasing'

      - name: Lint wasm32-wasip2 target
        run: cargo clippy --workspace --exclude hikari-render-service --exclude hikari-e2e --all-features --target wasm32-wasip2
        env:
          RUSTFLAGS: '--cfg releasing'

  test:
    name: Run tests
    runs-on: [self-hosted, linux, x64, local]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: sudo apt-get install -y libasound2-dev libudev-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-wasip2

      - name: Restore Rust Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Run cargo test
        run: cargo test --all-features --all
        env:
          RUSTFLAGS: '--cfg releasing'

      - name: Check wasm32-wasip2 target
        run: cargo check --workspace --exclude hikari-render-service --exclude hikari-e2e --all-features --target wasm32-wasip2
        env:
          RUSTFLAGS: '--cfg releasing'
