name: PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-title-check:
    uses: celestia-island/celestia-devtools/.github/workflows/pr-title-check.yml@master
